*
* Note to localizers: anything that doesn't end with "_LOC" should be left alone
*

*Any given #def may be used in several places; the notes on the
*"location" where it's used is mostly for the developer's benefit

*Constants from ODBC include files, used in chooseDataSource (Step 2)
#DEFINE SQL_FETCH_FIRST					0
#DEFINE SQL_FETCH_NEXT					1
#DEFINE SQL_SUCCESS						0
#DEFINE SQL_NO_DATA						100
#DEFINE SQL_ERROR						-1
#DEFINE SQL_DBMS_NAME					17
#DEFINE SQL_DBMS_VER					18
			
*These are used in wzusz.prg

#DEFINE NO_DISK_SPACE_LOC				"Espace disque insuffisant." && "Your computer is out of disk space."
#DEFINE DEVICE_SIZE_UNKNOWN 			-5		
#DEFINE RETRY_CANCEL					5
#DEFINE RETRY_CHOICE					4
#DEFINE RMT_OPERATOR					"?"
#DEFINE NOTHING_DO_LOC					"Pour terminer l'assistant Migration, vous devez choir soit de migre, soit de sauver le code SQL généré par l'Assistant Migration" && "To finish the Upsizing Wizard, you must choose either to upsize or to save the SQL code generated by the Upsizing Wizard."
#DEFINE CREATE_DBSQL_LOC 				"/* Créer la base de données */" && "/* Create database */"
#DEFINE CREATING_DATABASE_LOC 			"Création de la base de données '|1'" && "Creating database '|1'"
#DEFINE CREATE_DB_FAILED_LOC			"L'assistant Migration ne peut pas continuer parcequ'il na pas pu créer la base de données '|1'." && "The Upsizing Wizard cannot continue because it was unable to create the database '|1'."
#DEFINE ERROR_COMMENT_LOC				"Impossible de créer la base de données." && "Unable to create database."
#DEFINE TAKES_AWHILE_LOC				"Le serveur travaille. Ceci peut prendre quelques instants..." && "Server processing.  This may take a while..."
#DEFINE CREATING_TABLES_LOC				"Création des tables" && "Creating tables"
#DEFINE CANT_DROP2_LOC					"Impossible de supprimer la table" && "Unable to drop table."
#DEFINE CANT_CREATE_LOC					"Impossible de créer la table." && "Unable to create table."
#DEFINE CANT_CREATE_CLUST_LOC			"Impossible de créer le cluster." && "Unable to create cluster."
#DEFINE TABLE_NOT_CREATED_LOC			"Votre table n'a pas été migrée, parcequ'une table portant le même nom existe déjà sur le serveur." && "Your table was not upsized because a table of same name already exists on the server."
#DEFINE CLUST_NOT_CREATED_LOC 			"Le Cluster '|1' n'a pas été créé." && "Cluster '|1' was not created."
#DEFINE CLUST_IDX_FAILED_LOC			"Impossible de créer l'index cluster." && "Unable to create cluster index."
#DEFINE THIS_TABLE_LOC					"Table '|1'"
#DEFINE TABLE_SQL_LOC					"Génération de la table SQL" && "Generating table SQL"
#DEFINE CREATING_CLUST_SQL_LOC 			"Génération SQL pour les clusters" && "Generating SQL for clusters"
#DEFINE CREATING_CLUSTERS_LOC 			"Création des clusters" && "Creating clusters"
#DEFINE CLUST_EXISTS_LOC				"Le cluster n'a pas été créé, parcequ'un cluster du même nom existe déjà sur le serveur." && "The cluster was not created because a cluster of the same name already exists on the server."
#DEFINE CANT_DROP_LOC					"Impossible de supprimer le cluster" && "Unable to drop cluster."
#DEFINE THIS_CLUST_LOC					"Création du cluster '|1'" && "Creating cluster '|1'"
#DEFINE CLUST_INDEX_PREFIX 				"ic_"
#DEFINE TABLE_EXISTS_LOC	 			"La table '|1' existe déjà." + CHR(10)+CHR(13)+  "Ecraser?" && "Table '|1' already exists." + CHR(10)+CHR(13)+  "Overwrite?"
#DEFINE YES_LOC							"\<Oui" && "\<Yes"
#DEFINE YESALL_LOC						"Oui pour \<Tous" && "Yes to \<All"
#DEFINE NO_LOC							"\<Non" && "\<No"
#DEFINE CLUSTER_EXISTS_LOC			 	"Le cluster '|1' existe déjà." + chr(10)+chr(13)+ "Supprimer le cluster, toutes les tables et leurs"+chr(10)+chr(13)+"relations?" && "Cluster '|1' already exists." + CHR(10)+CHR(13)+  "Drop cluster, all tables and their" + ;
										CHR(10)+CHR(13) + "relations?"
#DEFINE SEND_DATA_LOC 					"Envoi des données" && "Sending data"
#DEFINE ERRT_LOC						"DErrTbl"
#DEFINE DATA_PROC_NAME					"rwf_insert_"
#DEFINE STARTING_COMMENT_LOC			"Création des index" && "Creating indexes"
#DEFINE TOO_MANY_FIELDS_LOC				"Le nombre de champs dans l'index local dépasse le maximum autorisé par le serveur" && "The number of fields in the local index exceeds the maximum allowed by the server."
#DEFINE INDEX_FAILED_LOC				"Impossible de créer l'index" && "Unable to create index."
#DEFINE TABLE_NOT_EXPORTED_LOC			"Impossible de créer l'index parceque la table n'a pas été correctement migrée." && "Unable to create index because the table was not successfully upsized."
#DEFINE CANT_CREATE_INDEX_LOC			"Impossible de créer l'index parceque les colonnes de booléens n'acceptent pas les index." && "Unable to create index because the indexes are not supported on bit columns."
#DEFINE ANALYZING_INDEXES_LOC			"Analyse des index locaux" && "Analyzing local indexes..."
#DEFINE SPROC_ERR_LOC					"Erreur pendant la création des procédures stockées depuis les règles de validation." && "Error creating stored procedure from validation rules."
#DEFINE DEFA_ERR_LOC					"Erreur de création des valeurs par défaut." && "Error creating default."
#DEFINE DRI_ERR_LOC						"Erreur de création des contraintes d'intégrité réferentielle." && "Error creating referential integrity constraint."
#DEFINE TRIG_ERR_LOC					"Erreur de création du trigger (déclencheur)" && "Error creating trigger."
#DEFINE GETTING_INFO_LOC 				"Récupération de l'information sur le dispositif depuis '|1'..."&& "Retrieving device information from '|1'..."
#DEFINE NEW_DEVICE_TOKEN_LOC 			"<Création d'un nouveau dispositif...>" && "<Create new device...>"
#DEFINE NEW_CLUSTER_TOKEN_LOC 			"<Création d'un nouveau cluster...>" && "<Create new cluster...>"
#DEFINE DEFAULT_LOC						"Défaut" && "Default"
#DEFINE DEVICE_SCRIPT_COMMENT_LOC		"/* Création de dispositif */" && "/* Create device */"
#DEFINE CANT_CREATE_DEVICE_LOC			"L'Assistant Migration ne peut pas continuer, parcequ'il ne peut pas créer de nouveau dispositif." && "The Upsizing Wizard cannot continue because it it is unable to create a new device."
#DEFINE SQS_ERR_DISK_INIT_FAIL  		5123		&&May occur if duplicate device name used
#DEFINE ALL_DONE_LOC					"Migration terminée." && "Upsizing complete."
#DEFINE TITLE_TEXT_LOC					"Assistant Migration" && "Upsizing Wizard"
#DEFINE CREATING_DBDEVICE_LOC			"Création du dispositif de base de données" && "Creating database device"
#DEFINE CREATING_LOGDEVICE_LOC			"Création du dispositif de journal" && "Creating log device"
#DEFINE DEVICE_ERR_COMMENT_LOC			"Impossible de créer le dispositif" && "Unable to create device."
#DEFINE CONNECT_FAILURE_LOC				"La migration ne peut pas continuer à cause d'une erreur de connexion.  Error |1." && "Upsizing cannot continue because a connection error occurred.  Error |1."
#DEFINE FAIL_SCRIPT_LOC					"Poursuivre la génération du code SQL malgré tout?" && "Continue generating SQL code anyway?"
#DEFINE QUERY_FAILURE_LOC				"L'assistant Migration ne peut pas continuer parce qu'une requète sur le serveur a échoué. Server error |1." && "The Upsizing Wizard cannot continue because a server query failed.  Server error |1."
#define LOCAL_SUFFIX_LOC 				"_local"
#DEFINE ANALYZING_FIELDS_LOC			"Analyse des tables sélectionnées pour l'exportation..." && "Analyzing tables selected for export..."
#DEFINE OPENED_EXCLUSIVE				108
#DEFINE EXCLUSIVE_LOC					"La table '|1' est déjà ouverte en exclusif par un autre utilisateur. L'assistant ne peut pas migrer cette table." && "The table '|1' has been opened exclusively by another user.  The Wizard cannot upsize this table."
#DEFINE TABLE_DELETED_LOC				"L'Assistant Migration ne peut pas trouver la table '|1'.  Cette table ne sera pas migrée." && "The Upsizing Wizard cannot locate the table '|1'.  This table will not be upsized."
#DEFINE TABLE_DELETED					1
#DEFINE DUP_CLUSTNAME_LOC 				"Le nom de cluster '|1' est déjà utilisé." && "The cluster name '|1' is already being used."
#DEFINE ONE_CLUSTER_LOC					"Une table ne peut être que dans un seul cluster. La table '|1' est déjà dans le cluster '|2'." && "A table can only be in one cluster.  The table '|1' is already in the cluster '|2'."
#DEFINE IDX_NOT_CREATED_LOC				"Le champ '|1' a été modifié vers un type de données ne supportant pas les index." && "Field '|1' changed to datatype that does not support indexes."
#DEFINE CANT_DROP_DEFA_LOC 				"Impossible de supprimer la valeur par défaut actuelle" && "Unable to drop existing default"
#DEFINE CANT_DROP_SPROC_LOC 			"Impossible de supprimer la procédure stockée actuelle." && "Unable to drop existing stored procedure."
#DEFINE INVALID_SQL_LOC					"Impossible de convertir l'expression locale dans la syntaxe du serveur." && "Unable to convert local expression to server syntax."
#DEFINE ORA_TRIG_PRE_LOC				"Trig_"
#DEFINE CONVERT_STEM_LOC				"Conversion" && "Converting"
#DEFINE CONVERT_RULE_LOC				"règles de validation" && " validation rules "
#DEFINE AND_LOC							"et" && "and"
#DEFINE CONVERT_DEFAS_LOC				" par défaut" && " defaults"
#DEFINE FTRIG_COMMENT_LOC 				"REGLE DE VALIDATION DE CHAMP POUR '|1'" && "FIELD VALIDATION RULE FOR '|1'"
#DEFINE TTRIG_COMMENT_LOC 				"REGLE DE VALIDATION DE TABLE" && "TABLE VALIDATION RULE"
#DEFINE TRIG_NAME 						"_test"
#DEFINE TBL_SPROC_PREFIX				"vrt_"
#DEFINE FLD_SPROC_PREFIX				"vrf_"
#DEFINE DEFLT_FLDMSG_LOC 				"La valeur de '|1' viole la règle de validation de colonne dans la table '|2'." && "Value in '|1' violates column validation rule on table '|2'."
#DEFINE DEFLT_TBLMSG_LOC 				"La valeur viole la règle de validation de table dans la table '|1'." && "Value violates table validation rule on table '|1'."
#DEFINE DEFAULT_PREFIX 					"Dflt_"
#DEFINE ZERO_DEFAULT_NAME 				"UW_ZeroDefault"
#DEFINE FOREIGN_KEY_PREFIX				"fk_"
#DEFINE PRIMARY_KEY_PREFIX				"pk_"
#DEFINE TABLE_HAS_LOC 					"la table a" && "table has"
#DEFINE TABLES_HAVE_LOC 				"les tables ont" && "tables have"
#DEFINE TWO_LONGS_WRONG_LOC 			"Oracle n'autorise qu'un seul champ de type LONG ou LONG RAW par table. Le champ '|1' a déjà ce type de données." && "Oracle allows only one field of type LONG or LONG RAW per table.;
The field '|1' currently has one of these data types."

#DEFINE LONG_TYPE_LOC 					"|1 |2  il y a plus d'un champ memo ou general. Les limites du serveur nécessitent de transformer certains de ces champs en données de longuer fixe." + CHR(10)+CHR(13)+CHR(10)+ CHR(13)+ ;
"Il se peut que les données dans ces champs dépassent ces longueurs. Vous pouvez modifier cette correspondance de champ à l'Etape 4 ou choisir d'annuler et de restructurer vos tables comme il est nécessaire." + CHR(10)+CHR(13)+CHR(10)+ CHR(13)+ ;
"Si vous constatez des dysfonctionnements dans la migration des données, vérifiez le réglage du Null dans la correspondance des champs General et Memo à l'étape Options del'Assistant." && "|1 |2 more than one memo or general field.  Server limits ;
require that some of these fields be mapped to fixed-length data types." + CHR(10)+CHR(13)+CHR(10)+ CHR(13)+ ;
"Data in some fields might exceed these lengths.  You can change this mapping in Step 4 or choose cancel ;
and then redesign your tables as needed." + CHR(10)+CHR(13)+CHR(10)+ CHR(13)+ ;
"If you are having trouble upsizing data, make sure to set Null mapping on Upsizing Options step to General and Memo field override."

*User-defined error numbers for RI triggers (same as Access Upsizing Wizard)
#DEFINE ERR_SVR_RULEVIO_SQL				"44444"
#DEFINE ERR_SVR_DELREFVIO	 			"44445"
#DEFINE ERR_SVR_UPDREFVIO				"44446"
#DEFINE ERR_SVR_INSREFVIO 				"44447"
#DEFINE ERR_SVR_DELREFVIO_ORA			"-20002"
#DEFINE ERR_SVR_UPDREFVIO_ORA			"-20003"
#DEFINE ERR_SVR_INSREFVIO_ORA			"-20004"
#DEFINE ERR_SVR_RULEVIO_ORA				"-20001"
#DEFINE	DEPENDENT_ROWS_LOC				"Impossible de supprimer ou de modifier l'enregistrement. Les règles d'intégrité référentielles seraient violées, parcequ'il existe un enregistrement lié dans la table '|1'." && "Cannot delete or change record.  Referential integrity rules would be violated because related records exist in table '|1'."
#DEFINE	CANT_ORPHAN_LOC 				"Impossible d'ajouter ou de modifier l'enregistrement. Les règles d'intégrité référentielles nécessitent un enregistrement lié dans la table '|1'." && "Cannot add or change record.  Referential integrity rules require a related record in table '|1'."
#DEFINE KEYS_MISMATCH_LOC				"Il n'y a pas le même nombre de champs dans les clés primaire et étrangère." && "Unequal number of fields in primary and foreign keys."
#DEFINE MULTIPLE_PKEYS_LOC				"La table '|1' est présente dans plusieurs relations avec des clés primaires différentes. Ceci n'est pas autorisé dans Oracle." && "Table '|1' is in multiple relationships using different primary keys.  This is not supported by Oracle."
#DEFINE REC_COUNT_VAR					"RecordCount"

*Constant comments for trigger code
#DEFINE PREVENT_M_UPDATES_LOC			"EMPECHE LES MISES A JOUR S'IL Y A DES ENREGISTREMENTS LIES DANS '|1'" && "PREVENT UPDATES IF DEPENDENT RECORDS IN '|1'"
#DEFINE PREVENT_DELETES_LOC 			"EMPECHE LES SUPPRESSIONS S'IL Y A DES ENREGISTREMENTS LIES DANS '|1'" && "PREVENT DELETES IF DEPENDENT RECORDS IN '|1'"
#DEFINE CASCADE_DELETES_LOC				"CASCADE LES SUPPRESSIONS VERS '|1'" && "CASCADE DELETES TO '|1'"
#DEFINE CASCADE_UPDATES_LOC				"CASCADE LES MISES A JOUR VERS '|1'" && "CASCADE UPDATES TO '|1'"
#DEFINE	PREVENT_INSERTS_LOC				"EMPECHE LES INSERTIONS S'IL N'Y A PAS DE CLE CORRESPONDANTE DANS '|1'" && "PREVENT INSERTS IF NO MATCHING KEY IN '|1'"
#DEFINE	PREVENT_C_UPDATES_LOC			"EMPECHE LES MISES A JOUR S'IL N'Y A PAS DE CLE CORRESPONDANTE DANS '|1'" && "PREVENT UPDATES IF NO MATCHING KEY IN '|1'"

*Oracle comments
#DEFINE ORA_PKEY_COMMENT_LOC			"Ajoute une clé primaire pour l'intégrité référentielle" && "/* Add primary key for referential integrity */"
#DEFINE ORA_FKEY_COMMENT_LOC			"Ajoute une clé étrangère pour l'intégrité référentielle" && "/* Add foreign key for referential integrity */"

*Thermometer comments
#DEFINE BUILDING_RI_LOC					"Génération de l'intégrité référentielle SQL" && "Generating referential integrity SQL"
#DEFINE RI_THIS_LOC						"Tables '|1' et '|2'" && "Tables '|1' and '|2'"

#DEFINE UTRIG_PREFIX					"TrigU_"
#DEFINE DTRIG_PREFIX 					"TrigD_"
#DEFINE ITRIG_PREFIX 					"TrigI_"
#DEFINE ORA_BIUD_TRIG_PREFIX			"Trig_BIUD_"
#DEFINE ORA_AUD_TRIG_PREFIX				"Trig_AUD_"
#DEFINE ORA_CONST_TAB_PREFIX			"Const_Tab_"
#DEFINE ORA_CONST_COL_PREFIX			"Const_Col_"
#DEFINE TBLRULE_COMMENT_LOC				"/* REGLE DE VALIDATION DE TABLE */" + CHR(10)&& "/* TABLE VALIDATION RULE */" + CHR(10)
#DEFINE FLDRULE_COMMENT_LOC				"/* REGLE DE VALIDATION DE CHAMP POUR '|1' */" + CHR(10) && "/* FIELD VALIDATION RULE FOR '|1' */" + CHR(10)
#DEFINE	ROLLBACK_LOC					"/* ANNULE LA TRANSACTION SI QUELQUECHOSE ECHOUE */" && "/* ROLLBACK THE TRANSACTION IF ANYTHING FAILED */"
#DEFINE	STATUS_COMMENT_LOC				"/* UTILISE PAR LES PROCEDURE STOCKEES DE VALIDATION */" && "/* USED BY VALIDATION STORED PROCEDURES */"
#DEFINE CREA_TRIGGERS_LOC				"Création des déclencheurs" && "Creating triggers"
#DEFINE UPDATE_PROP_FAILED_LOC			"Impossible de définir la propriété 'SendUpdates'." && "Unable to set the 'SendUpdates' property."
#DEFINE TABLES_PROP_FAILED_LOC			"Impossible de définir la propriété 'Tables'." && "Unable to set the 'Tables' property."
#DEFINE KEYFIELD_PROP_FAILED_LOC		"Impossible de définir la propriété Champ Clé dans '|1'." && "Unable to set Keyfield property on '|1'."
#DEFINE UPDATABLE_PROP_FAILED_LOC 		"Impossible de définir la propriété Updatable dans '|1'." && "Unable to set Updatable property on '|1'."
#DEFINE CONN_NAME_LOC					"Migration" && "Upsize"
#DEFINE NO_UNIQUEKEY_LOC				"Impossible de rendre la vue actualisable, parcequ'il n'y a pas d'index primaire ou candidat dans la table locale." && "Unable to make view updatable because no primary or candidate index exists on local table."
#DEFINE NEWDB_NAME_LOC					"Migration" && "Upsize"
#DEFINE ERROR_NAME_LOC 					"Erreurs_uw" && "Errors_uw"
#DEFINE MISC_NAME_LOC					"Divers_uw" && "Misc_uw"
#DEFINE FIELD_NAME_LOC					"Champs_uw" && "Fields_uw"
#DEFINE TABLE_NAME_LOC					"Tables_uw"
#DEFINE REL_NAME_LOC					"Relations_uw" && "Relationships_uw"
#DEFINE VIEW_NAME_LOC					"Vues_uw" && "Views_uw"
#DEFINE INDEX_NAME_LOC 					"Index_uw" && "Indexes_uw"
#DEFINE SCRIPT_NAME_LOC					"SQL_uw"
#DEFINE NEWPROJ_NAME_LOC 				"Rapport" && "Report"
#DEFINE ERR_REPORT_LOC 					"RptErreurs" && "RptErrs"
#DEFINE FIELDS_REPORT_LOC 				"RptChamps" && "RptField"
#DEFINE INDEX_REPORT_LOC 				"RptIndex"
#DEFINE RELS_REPORT_LOC 				"RptRels"
#DEFINE TABLES_REPORT_LOC 				"RptTable"
#DEFINE VIEWS_REPORT_LOC 				"RptVues" && "RptViews"
#DEFINE BUILDING_REPORT_LOC				"Création du rapport de migration" && "Creating upsizing report"
#DEFINE BUILDING_SCRIPT_LOC				"Création du script SQL" && "Creating SQL script"

#DEFINE CLUST_COMMENT_LOC				"Crée le cluster '|1'" && "Create cluster '|1'"
#DEFINE CLUST_INDEX_LOC					"Crée l'index cluster pour le cluster '|1'" && "Create cluster index for cluster '|1'"
#DEFINE TABLE_COMMENT_LOC				"Crée la table '|1'" && "Create table '|1'"
#DEFINE TRIGGER_COMMENT_LOC				"/* Code du Déclencheur */" && "/* Trigger code */"
#DEFINE INDEX_COMMENT_LOC				"/* Code de l'Index */" && "/* Index code */"
#DEFINE DEFAULT_COMMENT_LOC				"/* Code de la Valeur par Defaut */" && "/* Default code */"
#DEFINE SPROC_COMMENT_LOC				"/* code de la Procédure Stockée */" && "/* Stored procedure code */"
#DEFINE INVALID_NAME_LOC 				"Le nom que vous avez saisi est interdit. Merci de saisir un nouveau nom ou d'accepter le nom proposé." && "The name you entered isn't legal.  Please enter a new name or accept the name provided."
#DEFINE SEP_CHARACTER					"_"
#DEFINE MAX_DOSNAME_LEN					8
#DEFINE MAX_FIELDNAME_LEN				128
#DEFINE MAX_INDEX_FIELDS				16
#DEFINE ICON_EXCLAMATION				48
#DEFINE ICON_QUESTMARK					32
#DEFINE KEEP_GOING						6
#DEFINE MAX_NAME_LENGTH					30
#DEFINE YES_NO_BUTTONS					4
#DEFINE USER_YES						6
#DEFINE SUCCESS 						1
		
		
*These are used in the upsizing wizard formset class
#define STEP1_LOC	'Etape 1 - Choix de la Base de Données Locale' && 'Step 1 - Select Local Database'
#define STEP2_LOC	'Etape 2 - Choix de la Source de Données' && 'Step 2 - Select Data Source'
#define STEP3_LOC	'Etape 3 - Choix des Tables' && 'Step 3 - Choose Tables'
#define STEP4_LOC	'Etape 4 - Correspondance des Types de Données des Champs' && 'Step 4 - Map Field Data Types'

* Sql Server specific steps
#define STEP5_S_LOC	'Etape 5 - Choix de la Base de données de Destination' && 'Step 5 - Select Target Database'
#define STEP6_S_LOC	'Etape 6 - Définition des Propriétés de la Base de Données' && 'Step 6 - Set Database Properties'
#define STEP7_S_LOC	'Etape 7 - Précision des Propriétés du Journal' && 'Step 7 - Specify Log Properties'
#define STEP8_S_LOC 'Etape 8 - Définition des Options de Migration' && 'Step 8 - Set Upsizing Options'
#define STEP9_S_LOC 'Etape 9 - Fin' && 'Step 9 - Finish'

* Oracle specific steps
#define STEP5_O_LOC 'Etape 5 - Choix de l'Espace de Tables' && 'Step 5 - Select Tablespaces'
#define STEP6_O_LOC 'Etape 6 - Choix du Fichier d'espace de Tables' && 'Step 6 - Select Tablespace Files'
#define STEP7_O_LOC 'Etape 7 - Précision des Informations de Cluster' && 'Step 7 - Specify Cluster Information'
#define STEP8_O_LOC 'Etape 8 - Précision sur les Tables de Cluster' && 'Step 8 - Specify Cluster Tables'
#define STEP9_O_LOC 'Etape 9 - Précisions sur les Champs Clés de Cluster' && 'Step 9 - Specify Cluster Key Fields'
#define STEP10_O_LOC 'Etape 10 - Définition des Options de Migration' && 'Step 10 - Set Upsizing Options'
#define STEP11_O_LOC 'Etape 11 - Fin' && 'Step 11 - Finish'


#define DESC1_LOC 'Quelle base de données locale voulez-vous migrer?' && 'Which local database do you want to upsize?'
#define DESC2_LOC 'Vers quel type de serveur voulez-vous migrer votre base de données?' && 'Which data source do you want to upsize your database to?'
#define DESC3_LOC 'Choisssez sur le serveur distant une base de données vers laquelle vous voulez migrer, ou cliquez sur Nouveau et donnez un nom pour la nouvelle base de données.' && 'Select a database on the remote server that you want to upsize' + ;
				  ' to, or click New and name the new database.'
#define DESC4_LOC 'Sur quelle unité voulez-vous stocker votre nouvelle base de données, et quel espace voulez-vous lui réserver?' + ;
			CHR(13) + CHR(10) + CHR(13) + CHR(10) + ;
			'SQL Server a besoin de 2MB minimum par database. '&& 'Which device do you want to store the new database on, and how much' + ;
				  ' space do you want to allocate for it?' + ;
			CHR(13) + CHR(10) + CHR(13) + CHR(10) + ;
			'SQL Server requires a minimum of 2MB per database.'
#define DESC5_LOC 'Quelles sont les propriétés de votre journal optionnel de transaction?' + ;
			CHR(13) + CHR(10) + CHR(13) + CHR(10) + ;
			'Vous pouvez préciser l'unité et l'espace réservé pour ce journal.' && 'What are the properties for your optional tansaction log?' + ;
			CHR(13) + CHR(10) + CHR(13) + CHR(10) + ;
			'You can specify the device and allocate space for the log.'
#define DESC6_LOC 'Quelles tables voulez-vous migrer vers la base de données destination?' && 'Which tables do you want to upsize to the target database?'
#define DESC7_LOC 'Voulez-vous modifier la correspondance par défaut entre les types de données locales et ceux sur le serveur?' + ;
			CHR(13) + CHR(10) + CHR(13) + CHR(10) + ;
			'Pour changer un type de données sur le serveur, sélectionnez une table, cliquez sur la colonne Type sur le Serveur pour le champ à modifier, puis choisissez le type de données.' && 'Do you want to change the default mapping from local data types to server data types?' + ;
			CHR(13) + CHR(10) + CHR(13) + CHR(10) + ;
			'To change a server data type, select a table, click the Server Type column for the field you want to change, and then select a data type.'
#define DESC8_LOC 'Quelle option de migration voulez-vous spécifier?'  + ;
			CHR(13) + CHR(10) + CHR(13) + CHR(10) + ;
			'Vous pouvez spécifier les attributs de table que vous voulez migrer, et faire des changements locaux pour optimiser l'utilisation des données distantes.'&& 'Which upsizing option do you want to set?' + ;
			CHR(13) + CHR(10) + CHR(13) + CHR(10) + ;
			'You can set the table attributes you want to upsize and make local changes that optimize' + ;
			' using the remote data?'
#define DESC9_LOC 'Coisissez l'espace de tables que vous voulez migrer.' && 'Select the tablespaces you want to upsize to.'
#define DESC10_LOC 'Quels fichiers de données voulez-vous ajouter aux espaces de tables?' && 'Which data files do you want to add to the tablespaces?'
#define DESC11_LOC 'Migre et/ou crée les scripts SQL' && 'Upsize and/or create SQL scripts.'
#define DESC12_LOC 'Quels objets cluster voumez-vous créer?' + ;
				CHR(13) + CHR(10) + CHR(13) + CHR(10) + ;
				'Les clusters regroupent des tables liées; les tables d'un même cluster partageront la même clé de cluster.' && 'Which cluster objects do you want to create?' + ;
				CHR(13) + CHR(10) + CHR(13) + CHR(10) + ;
				'Clusters group together related tables; tables in the same cluster will share a common cluster key'
#define DESC13_LOC 'Quelles tables voulez-vous inclure dans les clusters?' + ;
				CHR(13) + CHR(10) + CHR(13) + CHR(10) + ;
				'Choisissez un cluster, puis choisissez une table disponible.' + ;
				CHR(13) + CHR(10) + ;
				'Pour ajouter des tables liées, cliquez sur Défaut. Pour chercher des clés de cluster possibles, sélectionnez des tables et cliquez sur Vérifier.' && 'Which tables do you want to include in clusters?' + ;
				CHR(13) + CHR(10) + CHR(13) + CHR(10) + ;
				'Select a cluster, and then select an available table.' + ;
				CHR(13) + CHR(10) + ;
				'To add related tables, click Default. To look for potential cluster keys, select tables and click Verify.'
#define DESC14_LOC 'Quels champs voulez-vous inclure dans la clé de cluster?' + ;
				CHR(13) + CHR(10) + ;
				'Choisissez un cluster et une table. L'ensemble des champs que vous sélectionnez dans la table deviendra le modèle de la clé de cluster.' && 'Which fields do you want to include in the cluster key?' + ;
				CHR(13) + CHR(10) + ;
				'Select a cluster and a table. The set of fields you select from the table become the pattern for the cluster key.'

#define CAPTION_UW 'Upsizing Wizard'
#define CAPTION_ORACLE 'Oracle Upsizing Wizard'
#define CAPTION_SQL 'SQL Server Upsizing Wizard'
#define CAPTION_ODBC 'Upsizing Wizard - ODBC Server'

#DEFINE GETTING_SERVER_DBS_LOC 			"Récupération des noms de bases de données sur '|1'..." && "Retrieving names of databases on '|1'..."
#DEFINE NEW_CLUSTERNAME_LOC 			"Nom du nouveau cluster:" && "Name of new cluster:"
#DEFINE HASH_CAPTION_LOC 				"Entrez la valeur des clés de hashage ou acceptez la valeur par défaut." && "Please enter value for hashkeys or accept default."
#DEFINE DONT_EXPORT 					7
#DEFINE YES_NO_CANC_BUTTONS				3
#DEFINE DONT_INDEX						6
#DEFINE CASCADE							6
#DEFINE TYPE_INDEX						1

#DEFINE TABLE_IN_CLUSTER_LOC 			"La table '|1' fait partie du cluster '|2'.  Si vous n'exportez pas '|1', ce cluster ne sera pas créé" ." + CHR(13)+CHR(10)  ;
+ CHR(13)+CHR(10)+"Voulez-vous exporter la table '|1'?"&& "The table '|1' is part of cluster '|2'.  If you don't export ;
'|1', this cluster will not be created." + CHR(13)+CHR(10)  ;
+ CHR(13)+CHR(10)+"Do you want to export table '|1'?"

#DEFINE CASCADE_TYPE_CHANGE_LOC			 "'|1' est un champ clé dans une ou plusieurs relations. Vous devriez modifier les champs clés reliés vers le même type de données que '|1'." && "'|1' is a key field in one or more relationships.  You may ;
want to change the related key fields to the same datatype as '|1'."

#DEFINE IN_INDEX_LOC					"Le type de données '|2' n'accepte pas l'indexation. Le champ '|1' figure dans un ou plusieurs index. Ceux-ci ne seront pas créés si vous changez le type de données en '|2'." + ;
CHR(10)+ CHR(13) + CHR(10) + CHR(13) + "Continuer?" && "The datatype '|2' does not support indexing.  The field '|1' is ;
in one or more indexes.  These will not be created if you change the field's datatype to '|2'." + ;
CHR(10)+ CHR(13) + CHR(10) + CHR(13) + "Continue?"

#DEFINE NO_NO_LOC						"Le type de données '|2' ne peut pas être indexé. Comme '|1' est un champ clé, ce changement est interdit." && "The datatype '|2' does not support indexing.  ;
Because '|1' is a key field, this change is not allowed."


*From the ChooseDataSource class
#DEFINE NO_DATASOURCES_DEFINED_LOC  "(Aucune source de données définie)" && "(No datasources defined)"
#DEFINE NO_CONNDEFS_DEFINED_LOC 	"(Aucune connexion définie)" && "(No connections defined)"
#DEFINE DELETE_DEVICE_INFO_LOC		"Si vous changez de source de données, vous perdrez une partie des informations que vous avez déjà données à l'assistant." + CHR(10) + CHR(13) + CHR(10) + CHR(13) + "Continuer?" && "If you change your datasource, you will lose some information you already provided the wizard." + CHR(10) + CHR(13) + CHR(10) + CHR(13) + "Continue?"
#DEFINE LOG_IN_FAILED_LOC 			"Impossible de se connecter à '|1'." && "Unable to connect to '|1'."
#DEFINE CHECK_PERMS_LOC				"Le serveur travaille..." && "Server processing..."
#DEFINE SQLCONN_FAIL_LOC			"Une erreur s'est produite en se connectant à '|1'." && "An error occurred connecting to '|1'."
#DEFINE ODBC 						1
#DEFINE ORA_NOT_COOL_LOC			"L'Assistant Migration ne supporte pas Oracle 6." && "The Upsizing Wizard does not support Oracle 6."
#DEFINE NO_USERID_LOC 				"Vous n'avez pas d'autorisation d'accès sur '|1'." && "You do not have an account on '|1'."

*From the ChooseSourceDB class
#DEFINE NO_DBS_LOC 					"<Aucune base de données ouverte>" && "<No database open>"
#DEFINE NO_SUCH_FILE_LOC	 		"Ce fichier n'existe pas." && "File does not exist."
#DEFINE LOCATE_LOC					"Localisez: |1" && "Locate: |1"

#DEFINE DUMP_ANALYSIS_INFO_LOC		"Vous avez modifié la base de données que vous migrez actuellement. Si vous continuez, les tables que vous avez sélectionnées pour la migration seront réinitialisées." + CHR(10) + CHR(13) + CHR(10) + CHR(13)+ "Continuer?" && "You have changed the database ;
you are upsizing.  If you continue, the tables you chose to ;
upsize will be reset." + CHR(10) + CHR(13) + CHR(10) + CHR(13)+ "Continue?"

*From the ChooseTargetDB class
#DEFINE EXISTING 					1
#DEFINE NEW_DB 						2
#DEFINE CANT_CONNECT_LOC			"Vous n'avez pas d'autorisation d'accès sur '|1'." && "You do not have an account on the database '|1'."
#DEFINE DUPLICATE_DBNAME_LOC 		"La base de données '|1' existe déjà. Merci de saisir un autre nom." && "The database '|1' already exists.  Please enter a different name."
#DEFINE NEW_LBL_DESC_LOC 			"Nouveau nom de la base de données:" && "New database name:"
#DEFINE EXISTING_LBL_DESC_LOC 		"Bases de données disponibles sur '|1':" && "Available databases on '|1':"
#DEFINE REALLY_CHANGE_TARGET_LOC	"Ne pas tenir compte de l'information d'unité pour la nouvelle base de données?" && "Discard device information for new database?"

*From the device class
#DEFINE DB_OR_LOG_TOO_BIG_LOC 		" la taille dépasse l'espace disponible sur l'unité spécifiée." && " size exceeds free space on selected device."
#DEFINE DATABASE_TXT_LOC			"Base de données" && "Database"
#DEFINE LOG_LOC						"Journal" && "Log"
#DEFINE DEVICE_TOO_BIG_LOC			" la taille dépasse l'espace disque disponible sur le serveur." && " device size exceeds available server disk space."
#DEFINE DB_TOO_SMALL_LOC			"Vous devez définir une taille de base de données de 2 mégabyte minimum." && "The database size you set needs to be 2 megabytes or larger."
#DEFINE SAME_DEVICE_LOC				"La base de données et le journal sont sur la même unité. Leurs tailles cumulées dépassent l'espace libre sur l'unité sélectionnée." && "Both the database and log are on the same device.  Their combined size exceeds the free space on the selected device."
#DEFINE DVCS_BOTH_TOO_BIG_LOC		"La taille combinée des deux unités que vous créez dépasse l'espace disque disponible sur le serveur." && "The combined size of the new devices you are creating exceeds available server disk space."
#DEFINE DEVICE_THING_LOC			"L'unité |1 fait partie de l'unité 'Default' choisie pour le |2.  A eux deux, le journal et la base de données ne doivent pas dépasser la taille de l'unité 'Default'." && "The |1 device is part of the 'Default' device chosen for the |2.  Together, the log and database cannot exceed the size of the 'Default' device."
#DEFINE DEVICE_AMBIGUITY_LOC		"L'assistant Migration ne peut pas mettre la base de données sur l'unité 'Default' et le journal sur une unité qui fait partie de l'unité 'Default'." && "The Upsizing Wizard cannot put the database on the 'Default' device and the log on a device that's part of the 'Default' device."
#DEFINE DISK_UNITS_LOC 				" MB"
#DEFINE DB_SIZE_LOC 				"Taille de la Base de Données:" && "Database Size: "
#DEFINE LOG_SIZE_LOC				"Taille du Journal:" && "Log Size: "
#DEFINE DB_DEVICE_CAPTION_LOC		"Unité de la Base de Données:" && "Database Device:"
#DEFINE LOG_DEVICE_CAPTION_LOC		"Unité du Journal:" && "Log Device:"
#DEFINE NO_DEVICE_NUMBERS_LOC 		"Le serveur n'a plus de nouvelle unité disponible." && "The server has no more device numbers available."
#DEFINE NEW_DEVICE_NAME_LOC 		"Nouveau nom d'unité:" && "New device name:"
#DEFINE NO_DEVICE_PERM_LOC			"Vous devez être administrateur du système pour créer une nouvelle unité." && "You must be a system administrator to create a new device."
#DEFINE USER_DEVICE 				-1			
#DEFINE OK_BUTTON					0

#DEFINE ERR_TBL_PREFIX_LOC			"ErreursExport_" && "ExportErrors_"
#DEFINE ERROR_COUNT_LOC				"erreurs" && "errors"
#DEFINE DATA_ERR_FRACTION			.1
#DEFINE DATA_ERR_MIN				100
#DEFINE DATA_ERRORS_LOC				"Des erreurs ont eu lieu pendant la migration. Voulez-vous enregistrer les tables contenant les information sur ces erreurs?" && "Errors occurred during upsizing.  Would you like to save the tables containing error information?"

#DEFINE LOG_FULL_LOC			"L'Assistant Migration ne peut pas continuer parceque le journal est plein." && "The Upsizing Wizard cannot continue because the log is full."
#DEFINE DEVICE_FULL_LOC			"L'Assistant Migration ne peut pas continuer parceque l'unité de la base de données est pleine." && "The Upsizing Wizard cannot continue because the database device is full."
#DEFINE SQL_BUG_LOC				"Quelqu'un a supprimé une unité sur le serveur. Le serveur doit redémarrer avant que vous ne puissiez créer de nouvelles unités." && "Someone has dropped a device on the server.  The server must be restarted before you can create any more devices."
#DEFINE VERS_NOT_SUPPORTED_LOC 	"L'Assistant Migration ne supporte pas SQL Server version 1.x" && "The Upsizing Wizard does not support SQL Server version 1.x"
#DEFINE NO_CREATEDB_PERM_LOC	"L'assistant Migration ne peut pas continuer parceque vous n'avez pas l'autorisation pour CREATE DATABASE sur '|1'." && "The Upsizing Wizard cannot continue because you do not have CREATE DATABASE permissions on '|1'."
#DEFINE PREVENT_SELF_O_LOC		"EMPECHE LES INSERTIONS ET LES MISES A JOUR SI AUCUNE CLE NE CORRESPOND DANS '|1'" && "PREVENT INSERTS AND UPDATES IF NO MATCHING KEY IN '|1'"
#DEFINE AVAIL_DSOURCE_LOC		"Sources de données disponibles:" && "Available Data Sources:"
#DEFINE CONNS_INDB_LOC			"Connexions existantes:" && "Existing Connections:"
#DEFINE LOG_SIZE_CAPT_LOC		"Taille du Journal:" && "Log Size:"


#DEFINE UNKNOWN_SERV_ERROR		"The Upsizing Wizard cannot continue because server error '|1' occurred."
#DEFINE LACKING_PERMS_LOC		"Avec vos autorisations sur la base de données '|1', l'Assistant Migration ne pourra pas " && "With your permissions on the database '|1' the Upsizing Wizard will be unable to "
#DEFINE OR_LOC					" ou " && " or "

#DEFINE CANT_CREATE_TABLE		"create tables"
#DEFINE CANT_CREATE_DEFAS		"create defaults" 
#DEFINE CANT_CREATE_SPROCS		"create stored procedures"

#DEFINE RMTZING_VIEW_LOC		"Redirection des vues locales" && "Redirecting local views"
#DEFINE RMTZING_TABLE_LOC		"Création des vues distantes sur les tables" && "Creating remote views based on tables"

#DEFINE CANT_CREATE_INDEX		"create indexes"
#DEFINE CANT_CREATE_TRIGGER		"create triggers"

#DEFINE THIS_VIEW_LOC			"Vue '|1'" && "View '|1'"

#DEFINE DEXPORT_FAILED_LOC		"L'exportation des données est interrompue à cause d'erreurs d'exportation." && "Data export halted because of export errors."
#DEFINE SOME_ERRS_LOC			"|1 enregistrements n'ont pas été exportés correctement." && "|1 records not exported successfully."
#DEFINE DATA_EXPORT_LOC			"Exportation des données" && "Data export"
#DEFINE CLUSTER_LOC				"Cluster"
#DEFINE TABLE_LOC				"Table"
#DEFINE TRIGGER_LOC				"Déclencheur" && "Trigger"
#DEFINE DEFAULT_LOC				"Défaut" && "Default"
#DEFINE TABLE_RULE_LOC			"Règle de validation de table" && "Table validation rule"
#DEFINE FIELD_RULE_LOC			"Règele de validation de champ" && "Field validation rule"
#DEFINE RI_LOC					"Intégrité référentielle" && "Referential integrity"
#DEFINE INDEX_LOC				"Index"
#DEFINE RECORD_EXP_LOC			"Exportation de données" && "Data export"
#DEFINE CONVTO_TRIG_ERR_LOC		"Imposible de convertir la règle à déclencher." && "Unable to convert rule to trigger."
#DEFINE RECCOUNT_LOC			"enregistrements exportés" && "records exported"
#DEFINE CANCELED_LOC			"Annulé" && "Canceled"
#DEFINE PREP_ERR_LOC			"Enregistrement de l'information sur l'erreur." && "Storing error information."
#DEFINE SCRIPT_INDB_LOC			"Création de la base e données et du projet pour le SQL généré." && "Creating database and project for generated SQL."
#DEFINE PREP_ERRTBLS_LOC		"Enregistrement de l'information sur l'erreur." && "Storing error information."
#DEFINE ESCAPE_CONT_LOC			"Abandonner l'Assistant Migration?" && "Cancel Upsizing Wizard?"

#DEFINE RMTIZE_VIEW_FAILED_LOC	"Vue locale non convertie en vue distante." && "Local view not converted to remote view."
#DEFINE VIEW_LOC				"Vue" && "View"
#DEFINE VIEW_PROPS_FAILED_LOC	"Echec de la définition des propriétés des vues distantes." && "Setting of properties on remote views failed."
#DEFINE FATAL_ODBCERR_LOC		"L'Assistant Migration ne peut pas continuer parcequ'une erreur ODBC est arrivée." && "The Upsizing Wizard cannot continue because an ODBC error has occurred."
#DEFINE CANT_OPENDB_LOC			"Impossible d'ouvrir '|1'." && "Unable to open '|1'."
#DEFINE F_ACC_DENIED_LOC		"Accès au fichier interdit." && "File access denied."
#DEFINE DEVICE_STUFF_FAILED_LOC	"L'Assistant Migration ne peut pas continuer, parcequ'il n'a pas pu récupérer l'information sur l'unité." && "The Upsizing Wizard cannot continue because it was unable to retrieve device information."
#DEFINE cascade_char_loc 		"C"
#DEFINE restrict_char_loc 		"R"
#DEFINE ignore_char_loc			"I"

#DEFINE NO_OPEN_EXCLU_LOC		"L'Assistant Migration n'a pas pu ouvrir toutes les tables de la base de données. Vous devriez lancer un VALIDATE DATABASE sur votre base de données." && "The Upsizing Wizard was not able to open all database tables.  These will not be available for upsizing.  You may want to run the VALIDATE DATABASE command on your database."

#DEFINE BIND_DEFAS_LOC			"Liaison de valeurs par défaut des champs logiques" && "Binding defaults to bit fields"
#DEFINE ZD_DESC_LOC				"/* Cette valeur par défaut zéro est liée à un ou plusieurs champs. */" && "/* This zero default is bound to one or more fields.  */"

#DEFINE NO_MULTIPLE_LOC 		gcQT + "|1 concernant plusieurs enregistrements de '|2' est interdi à cause des contraintes d'intégrité référentielles."   + gcQT&& gcQT + "|1 affecting multiple records in '|2' not allowed because of referential integrity constraints."  + gcQT
#DEFINE NO_MULTI_TITLE_LOC 		"EMPECHER |1 CONCERNE PLUSIEURS ENREGISTREMENTS" && "PREVENT |1 AFFECTING MULTIPLE RECORDS"
#DEFINE UPDATES_LOC 			"METTRE à JOUR" && "UPDATEs"
#DEFINE DELETES_LOC				"SUPPRIMER" && "DELETEs"

#define KP_BACKSPACE	127
#define KP_TAB			9
#define KP_ENTER		13
#define KP_ESCAPE		27
#define KP_LEFTARROW	19
#define KP_RIGHTARROW	4
#define KP_UPARROW		5
#define KP_DOWNARROW	24
#define KP_DELETE		7
#define KP_HOME			1
#define KP_END			6
#define KP_INSERT		22

#define KP_SHIFT_HOME	55
#define KP_SHIFT_END	49
#define KP_SHIFT_TAB	15

#define KP_BACKTAB				15
#define KP_ESCAPE				27
#define KP_NEXT					305
#define KP_BACK					304
#define KP_FINISH				289

#DEFINE SUPPORT_ORACLE			.T.

#DEFINE NEW_DIRNAME_LOC			"Migrer" && "Upsize"
#DEFINE REQ_PROVERSION_LOC 		"L'Assistant Migration nécessite l'édition professionnelle de Visual FoxPro." && "The Upsizing Wizard requires the Professional edition of Visual FoxPro."

#DEFINE MAX_FIELDS				255
#DEFINE MIN_DEVICESIZE_LOC		"Vous devez définir une taille d'unité de 2 mégabytes au moins." && "You must set the size of the device to 2 megabytes or larger."

#DEFINE SQL_ALLOCERR_LOC		"L'Assistant Migration ne peut pas continuer parceque l'ODBC n'a pas pu démarrer." && "The Upsizing Wizard cannot continue because ODBC could not be started."

#DEFINE NO_ODBC_LOC				"L'Assistant Migration nécessite l'ODBC, qui n'est pas installé actuellement." && "The Upsizing Wizard requires ODBC, which is not currently installed."

* For Advanced Export Options class (jvf)
#DEFINE VIEW_PREFIX_REQD_LOC    "Vous devez fournir un préfixe pour le nom de la vue, ou choisir Aucun." &&    "You must supply a prefix for the view name, or choose None."
#DEFINE VIEW__NAME_SUFFIX_REQD_LOC "Vous devez fournir un suffixe pour le nom de la vue, ou choisir Aucun." && "You must supply a suffix for the view name, or choose None."
#DEFINE DROP_TABLE_WARNING_LOC "Vous avez choisi de supprimer les tables locales! Avez-vous bien vérifié que vous avez une sauvegarde récente de la base de données locale avnt de continuer l'Assistant?" && "You have chosen to Drop Local Tables! " + ;
		"You should make sure you have a recent backup of the local database before completing the Wizard."
#DEFINE VIEW_NAME_DUPE_SUFFIX_LOC LOCAL_SUFFIX_LOC + "est le suffixe par défaut utilisé par l'Assistant Migration pour renommer les tables locales. Vous devez ou bien changer ce suffixe, ou bien choisir de Supprimer les Tables Locales." && + " is the default suffix the Upsizng Wizard uses when renaming local tables. " + ;
		"You must either change this suffix or choose to Drop Local Tables."

* For checking if ODBC is installed
#DEFINE DLLPATH_32S				"\SYSTEM\WIN32S\"
#DEFINE DLLPATH_NT				"\SYSTEM32\"
#DEFINE DLLPATH_WIN95			"\SYSTEM\"
#DEFINE DLL_ODBC				"ODBC32.DLL"

#DEFINE NOT_EXCLUSIBLE_LOC		"Les bases de données qui ne sont pas ouvertes en exclusif ne sont pas disponibles pour la migration." && "Databases which are not opened exclusively will not be available for upsizing."

#DEFINE NEED_SQL6DRVR_LOC		"Pour migrer vers SQL Server 6.x, merci d'installer un pilote ODBC pour SQL Server d'une version 2.05 ou supérieure." && "To upsize to SQL Server 6.x, please install a SQL Server ODBC driver version 2.05 or later."

#DEFINE TIMESTAMP_LOC			"Timestamp_colonne" && "Timestamp_column"
#DEFINE FIELDS_UNEQUAL_LOC		"Impossible de définir les propriétés de champ, parceque les vues locale et distante n'ont pas le même nombre de champs." && "Unable to set field properties because remote and local views have an unequal number of fields."


#DEFINE	CANT_OPEN_EXCLU_LOC		"Impossible d'ouvrir '|1' en exclusif." && "Unable to open '|1' exclusively."

#DEFINE DB_GONE_LOC				"La base de données '|1' de la définition de connexion chosie n'existe plus. Merci de choisir une autre définition." && "The database '|1' in the selected connection definition no longer exists.  Please choose a different definition."
#DEFINE SQL_SERVER				"SQL Server"
#DEFINE ORACLE_SERVER			"Oracle"
#DEFINE MS_SERVER				"MS"
#DEFINE UNKNOWN_SERVER			""

#DEFINE KB_LABEL				"  KB"
#DEFINE CREATING_TABLESPACE_LOC "Création de l'espace de tables '|1'" && 			"Creating tablespace '|1'"
#DEFINE NO_CREATETS_PERM_LOC	"L'Assistant Migration ne peut pas continuer, parceque vous n'avez pas l'autorisation de CREATE TABLESPACE sur '|1'." && "The Upsizing Wizard cannot continue because you do not have CREATE TABLESPACE permissions on '|1'."
#DEFINE CREATE_TS_FAILED_LOC	"L'Assistant Migration ne peut pas continuer parcequ'il n'a pas pu créer l'espace de tables '|1'." && "The Upsizing Wizard cannot continue because it was unable to create the tablespace '|1'."
#DEFINE CREATE_TSSQL_LOC 		"/* Crée l'espace de tables */" && "/* Create tablespace */"

#DEFINE CLUSTER_TABLE_F_LOC		"Echec de la vérification. Les tables sélectionnées pour le cluster '|1' ne peuvent pas avoir de clé commune" && "Verification failed. Tables selected for cluster '|1' cannot have a common key"
#DEFINE CLUSTER_TABLE_T_LOC		"Vérification réussie. Les tables sélectionnées pour le cluster '|1' peuvent avoir une clé commune" && "Verification succeded. Tables selected for cluster '|1' may have a common key"
#DEFINE CLUSTER_KEY_F_LOC		"Echec de la vérification. La clé de cluster pour le cluster '|1' ne convient pas pour les tables du cluster" && "Verification failed. Cluster key for cluster '|1' is not consistent across cluster tables"
#DEFINE CLUSTER_KEY_T_LOC		"Vérification réussie. La clé de cluster pour le cluster '|1' convient pour les tables du cluster" && "Verification succeded. Cluster key for cluster '|1' is consistent across cluster tables"
#DEFINE CANT_PERMISSION_LOC		"Impossible de retrouver les autorisations." && "Unable to retrive permissions"

#DEFINE INVALID_SERVER_LOC		"Le type du Serveur n'est pas '|1'. Choisissez une autre source de données." && "Server type is not '|1'. Select another datasource."
#DEFINE CL_LOC					"cl_"
#DEFINE IDENTCOL_LOC			"Identite_colonne" && "Identity_column"
#DEFINE CANT_UPSIZE_LOC			"La table '|1' ne peut pas être migrée:" && "Table '|1' may not be upsized:"
#DEFINE EXCEED_FIELDS_LOC		"le nombre de champs dépasse 250" && "the number of fields exceed 250"
#DEFINE EXCEED_RECSIZE_LOC		"la taille de l'enregistrement dépasse 1962" && "the record size exceed 1962"
#DEFINE CANTDEFCLUSTERS_LOC		"Impossible de définir les clusters par défaut. Aucune relation entre les tables trouvée." && "Unable to create default clusters. No relations between tables were found."
#DEFINE CANTUPSIZE_TABLE_LOC	"L'Assistant Migration n'a pas pu migrer les tables:" && "The Upsizing Wizard was unable to upsize tables: "

*Oracle permissions
#DEFINE LACKING_PERMS_ORA		"Vous n'avez pas les permissions suivantes, qui sont nécessaires à l'Assistant Migration:" && "You don't have the following permissions that may be required by the Upsizing Wizard: "

#DEFINE CANT_CREATE_OTABLE_LOC	"CREATE TABLE"
#DEFINE CANT_CREATE_TABLESPACE_LOC	"CREATE TABLESPACE"
#DEFINE CANT_ALTER_TABLESPACE_LOC	"ALTER TABLESPACE"
#DEFINE CANT_UNLIMITED_TS_LOC	"UNLIMITED TABLESPACE"
#DEFINE CANT_CREATE_OCLUST_LOC	"CREATE CLUSTER"
#DEFINE CANT_CREATE_ORAINDEX_LOC "CREATE ANY INDEX"
#DEFINE CANT_CREATE_TRIGGER_LOC	"CREATE TRIGGER"
#DEFINE CANT_CREATE_OPROC_LOC	"CREATE PROCEDURE"

#DEFINE NO_SQL7UPSIZEMASTER_LOC	"L'Assistant Migration ne peut pas migrer vers la base de données Master de SQL Server 7.0." && "The Upsizing Wizard does not support upsizing to the SQL Server 7.0 Master database."
* #DEFINE NO_SQL7BADCOMPLEVEL_LOC  "The Upsizing Wizard could not set the SQL Server 7.0 database to proper compatibility level for upsizing."

#define NO_SQL7BADCOMPLEVEL_LOC "L'Assistant Migration n'a pas réussi à mettre la base de données SQL Server 7.0 au niveau de compatibilité correct pour la migration."+ CHR(10) + CHR(10) + ;
 " Pour migrer, Visual FoxPro doit mettre le niveau de compatiblité de la base de données cible dans SQL à 6.5" + CHR(10) + CHR(10) + ;
 "Ceci est réalisé par l'appel de la procédure stockée sp_dbcmptlevel sur le Serveur SQL. Il n'y a que le DBO, les membres du role déterminé sysadmin, et le db_owner déterminé pour la base de données, qui puissent exécuter cette procédure."+ CHR(10) + CHR(10) + ;
 " Vérifez que l'accès SQL que vous utilisez dispose bien des droits nécessaires à cette action." &&"The Upsizing Wizard could not set the SQL Server database to proper compatibility level for upsizing." + CHR(10) + CHR(10) + ;
 "In order to upsize, Visual FoxPro must set the compatibility level of the target SQL database to 6.5." + CHR(10) + CHR(10) + ;
 "This is done by calling the sp_dbcmptlevel stored procedure on SQL Server." + ;
 "  Only the DBO, members of the sysadmin fixed server role, and the db_owner fixed " + ;
 "database role (if the database whose compatibility level is to be changed is the " + ;
 "current database) can execute this procedure." + CHR(10) + CHR(10) + ;
 "Please ensure the SQL login you are " + ;
 "using has the appropriate rights to perform this action."

 
#DEFINE NO_SQL7NONEWDB_LOC "L'Assistant Migration n'autorise pas la création de nouvelles bases de données pour SQL Server 7.0 ou supérieur." && "The Upsizing Wizard does not support creation of new databases for SQL Server 7.0 or higher." 