LPARAMETERS TCSUBKEY, TNINDEX, TNTYPE
LOCAL LCSUBKEY, LCRETURN, LNRESULT, LCDATABUFFER
TNTYPE = IIF(TYPE("tnType")="N", TNTYPE, 0)
LNREGHANDLE = 0
LNRESULT = REGOPENKEY(-2147483647, TCSUBKEY, @LNREGHANDLE)
IF LNRESULT<>0
RETURN .NULL.
ENDIF
TCSUBKEY = SPACE(256)
TCVALUE = SPACE(256)
LNSIZE = 256
LNVALSIZE = 256
LNRETURN = REGENUMVALUE(LNREGHANDLE, TNINDEX, @TCSUBKEY, @LNVALSIZE, 0, @TNTYPE, @TCVALUE, @LNSIZE)
= REGCLOSEKEY(LNREGHANDLE)
IF LNRESULT<>0
RETURN .NULL.
ENDIF
RETURN LEFT(TCVALUE, ATC(CHR(0), TCVALUE)-1)
ENDFUNC
**
