**
FUNCTION GKCGetRGBValues
LPARAMETERS PNRGBVALUE
LOCAL LCRGBSTRING
LCRGBSTRING = GETRVALUE(PNRGBVALUE)+","+GETBVALUE(PNRGBVALUE)+","+GETGVALUE(PNRGBVALUE)
RETURN LCRGBSTRING
ENDFUNC
**
FUNCTION GetRValue
LPARAMETERS PNRGBCOLORVALUE
LOCAL LNRVALUE, LNNDX
LNRVALUE = PNRGBCOLORVALUE
FOR LNNDX = 8 TO 31
LNRVALUE = BITCLEAR(LNRVALUE, LNNDX)
ENDFOR
RETURN TRANSFORM(INT(LNRVALUE))
ENDFUNC
**
FUNCTION GetGValue
LPARAMETERS PNRGBCOLORVALUE
LOCAL LNBVALUE, LNNDX
LNBVALUE = BITRSHIFT(PNRGBCOLORVALUE, 16)
FOR LNNDX = 8 TO 31
LNBVALUE = BITCLEAR(LNBVALUE, LNNDX)
ENDFOR
RETURN TRANSFORM(INT(LNBVALUE))
ENDFUNC
**
FUNCTION GetBValue
LPARAMETERS PNRGBCOLORVALUE
LOCAL LNGVALUE, LNNDX
LNGVALUE = BITRSHIFT(PNRGBCOLORVALUE, 8)
FOR LNNDX = 8 TO 31
LNGVALUE = BITCLEAR(LNGVALUE, LNNDX)
ENDFOR
RETURN TRANSFORM(INT(LNGVALUE))
ENDFUNC
**
