**
FUNCTION GKCGetMACAddress
LOCAL LLPGUID, LRGUID
LPGUID = REPLICATE(CHR(0), 16)
LRGUID = REPLICATE(CHR(0), 80)
IF "5."$OS()
IF UUIDCREATESEQUENTIAL(@LPGUID)=0 .AND. STRINGFROMGUID2(LPGUID, @LRGUID, 40)<>0
LCMACADDRESS = SUBSTR(STRCONV(LEFT(LRGUID, 76), 6), 26, 12)
ELSE
LCMACADDRESS = ""
ENDIF
ELSE
IF COCREATEGUID(@LPGUID)=0 .AND. STRINGFROMGUID2(LPGUID, @LRGUID, 40)<>0
LCMACADDRESS = SUBSTR(STRCONV(LEFT(LRGUID, 76), 6), 26, 12)
ELSE
LCMACADDRESS = ""
ENDIF
ENDIF
RETURN LCMACADDRESS
ENDFUNC
**
