**
FUNCTION GKCGetStockName
LPARAMETERS TCNAME
LOCAL LCNAME, LOEXCEPTION
TRY
IF SEEK(UPPER(TCNAME), "gkcmethodlist", "name")
LCNAME = ALLTRIM(GKCMETHODLIST.NAME)
ELSE
LCNAME = ""
ENDIF
CATCH TO LOEXCEPTION
LCNAME = ""
ENDTRY
RETURN LCNAME
ENDFUNC
**
