**
FUNCTION GKCGetToolsPath
LPARAMETERS TCKEY, TCFILENAME
LOCAL LCPATH
LCPATH = GKCGETREGSTRING_HKCU("Software\GKC Industries\GKC Tools", TCKEY)
IF EMPTY(LCPATH)
DO FORM GKCLocFile TO LCPATH WITH TCFILENAME
IF ISNULL(LCPATH) .OR. EMPTY(LCPATH)
ELSE
= GKCSETREGSTRING_HKCU("Software\GKC Industries\GKC Tools", TCKEY, JUSTPATH(LCPATH))
ENDIF
ELSE
LCPATH = ADDBS(LCPATH)+TCFILENAME
ENDIF
RETURN LCPATH
ENDFUNC
**
