**
FUNCTION GKCOpenFDKEYWRD
LOCAL LCFILENAME, LLRETURN
IF USED('fdkeywrd')
LLRETURN = .T.
SELECT FDKEYWRD
ELSE
LCFILENAME = "FDKEYWRD.DBF"
TRY
USE SHARED (LCFILENAME) ALIAS FDKEYWRD ORDER token IN 0
SELECT FDKEYWRD
LLRETURN = .T.
CATCH TO LOEXCEPTION
LCFILENAME = SYS(2004)+"FDKEYWRD.DBF"
TRY
USE SHARED (LCFILENAME) ALIAS FDKEYWRD ORDER token IN 0
SELECT FDKEYWRD
LLRETURN = .T.
CATCH TO LOEXCEPTION
LCFILENAME = SYS(2004)+"WIZARDS\FDKEYWRD.DBF"
TRY
USE SHARED (LCFILENAME) ALIAS FDKEYWRD ORDER token IN 0
SELECT FDKEYWRD
LLRETURN = .T.
CATCH TO LOEXCEPTION
LLRETURN = .F.
ENDTRY
ENDTRY
ENDTRY
ENDIF
RETURN LLRETURN
ENDFUNC
**
