**
DEFINE CLASS GKCOption AS OptionButton
AUTOSIZE = .T.
CAPTION = "GKCOption"
BACKSTYLE = 0
**
PROCEDURE GotFocus
THIS.FONTBOLD = .T.
ENDPROC
**
PROCEDURE LostFocus
THIS.FONTBOLD = .F.
ENDPROC
**
PROCEDURE MouseEnter
LPARAMETERS NBUTTON, NSHIFT, NXCOORD, NYCOORD
THIS.FONTBOLD = .T.
ENDPROC
**
PROCEDURE MouseLeave
LPARAMETERS NBUTTON, NSHIFT, NXCOORD, NYCOORD
THIS.FONTBOLD = .F.
ENDPROC
**
ENDDEFINE
**
