**
FUNCTION GKCRTFAddLineNumbers
LPARAMETERS PCRTFTEXT, PNBEGLINE, PNENDLINE
LOCAL LNPOS, LNNDX, LNLAST, LNBEG, LNEND, LCPREVCF
LNPOS = ATC(";}}", PCRTFTEXT)
IF LNPOS>0
DO WHILE SUBSTR(PCRTFTEXT, LNPOS, 1)<>" "
LNPOS = LNPOS+1
ENDDO
PCRTFTEXT = STUFF(PCRTFTEXT, LNPOS, 0, "\cf0 "+TRANSFORM(PNBEGLINE)+"\tab")
LNLAST = LNPOS
PNBEGLINE = PNBEGLINE+1
LNNDX = 1
LNPOS = ATC("\par", PCRTFTEXT, LNNDX)
DO WHILE LNPOS>0
LNBEG = LNPOS
DO WHILE .T.
LNBEG = LNBEG-1
IF SUBSTR(PCRTFTEXT, LNBEG, 3)="\cf"
LNEND = LNBEG+3
DO WHILE .T.
LNEND = LNEND+1
IF INLIST(SUBSTR(PCRTFTEXT, LNEND, 1), " ", "\")
LCPREVCF = SUBSTR(PCRTFTEXT, LNBEG, LNEND-LNBEG)
EXIT
ENDIF
IF LNEND=LEN(PCRTFTEXT)
LCPREVCF = ""
EXIT
ENDIF
ENDDO
EXIT
ENDIF
IF LNBEG=LNLAST
LCPREVCF = ""
EXIT
ENDIF
ENDDO
PCRTFTEXT = STUFF(PCRTFTEXT, LNPOS+4, 0, "\cf0 "+TRANSFORM(PNBEGLINE)+"\tab"+LCPREVCF)
LNNDX = LNNDX+1
PNBEGLINE = PNBEGLINE+1
LNPOS = ATC("\par", PCRTFTEXT, LNNDX)
ENDDO
ENDIF
RETURN PCRTFTEXT
ENDFUNC
**
