**
FUNCTION GKCStripWhitespace
LPARAMETERS PCLINE
PCLINE = ALLTRIM(PCLINE, 1, " ", CHR(9))
DO WHILE ATC(CHR(9), PCLINE)>0
PCLINE = CHRTRAN(PCLINE, CHR(9), " ")
ENDDO
DO WHILE ATC("  ", PCLINE)>0
PCLINE = STRTRAN(PCLINE, "  ", " ")
ENDDO
RETURN PCLINE
ENDFUNC
**
