**
FUNCTION GKCSetRegString_HKCU
LPARAMETERS TCSUBKEY, TCENTRY, PCSTRVALUE
LOCAL LNREGHANDLE, LNRESULT, LNSIZE, LCDATABUFFER, TNTYPE, LCSTRBUFFER, LNINTVALUE, LNDECVALUE
DO CASE
CASE VARTYPE(PCSTRVALUE)="C"
LCSTRBUFFER = ALLTRIM(PCSTRVALUE)
CASE VARTYPE(PCSTRVALUE)="N"
LNINTVALUE = INT(PCSTRVALUE)
LNDECVALUE = (PCSTRVALUE-LNINTVALUE)*10000
LCSTRBUFFER = TRANSFORM(LNINTVALUE)+"."+TRANSFORM(LNDECVALUE)
CASE VARTYPE(PCSTRVALUE)="D"
LCSTRBUFFER = DTOC(PCSTRVALUE)
CASE VARTYPE(PCSTRVALUE)="T"
LCSTRBUFFER = TTOC(PCSTRVALUE)
CASE VARTYPE(PCSTRVALUE)="L"
IF PCSTRVALUE
LCSTRBUFFER = ".T."
ELSE
LCSTRBUFFER = ".F."
ENDIF
CASE VARTYPE(PCSTRVALUE)="Y"
LCSTRBUFFER = TRANSFORM(PCSTRVALUE)
OTHERWISE
LCSTRBUFFER = PCSTRVALUE
ENDCASE
LNREGHANDLE = 0
LNRESULT = REGOPENKEY(-2147483647, TCSUBKEY, @LNREGHANDLE)
IF LNRESULT<>0
LNRESULT = REGCREATEKEY(-2147483647, TCSUBKEY, @LNREGHANDLE)
IF LNRESULT<>0
RETURN .NULL.
ENDIF
ENDIF
IF  .NOT. ISNULL(LCSTRBUFFER)
LNSIZE = LEN(LCSTRBUFFER)
LNRESULT = REGSETVALUEEX(LNREGHANDLE, TCENTRY, 0, 1, LCSTRBUFFER, LNSIZE)
ELSE
LNRESULT = REGDELETEVALUE(LNREGHANDLE, TCENTRY)
ENDIF
= REGCLOSEKEY(LNREGHANDLE)
IF LNRESULT<>0
RETURN .NULL.
ENDIF
RETURN .T.
ENDFUNC
**
