LPARAMETERS TOOBJECT, TCNAME, TVCLASS, TVCLASSLIBRARY
LOCAL LCNAME, LCCLASS, LCCLASSLIBRARY, OOBJECT, LNCOUNT
LOCAL LNOBJECTREFINDEX, LNOBJECTREFCOUNT, OEXISTINGOBJECT
IF TYPE("toObject")<>"O" .OR. ISNULL(TOOBJECT)
RETURN .NULL.
ENDIF
LCNAME = IIF(TYPE("tcName")=="C", ALLTRIM(TCNAME), LOWER(SYS(2015)))
OEXISTINGOBJECT = .NULL.
OOBJECT = .NULL.
LCCLASSLIBRARY = ""
DO CASE
CASE TYPE("tvClass")=="O"
OOBJECT = TVCLASS
LCCLASS = LOWER(OOBJECT.CLASS)
LCCLASSLIBRARY = LOWER(OOBJECT.CLASSLIBRARY)
IF  .NOT. ISNULL(OEXISTINGOBJECT) .AND. LOWER(OEXISTINGOBJECT.CLASS)==LCCLASS .AND. LOWER(OEXISTINGOBJECT.CLASSLIBRARY)==LCCLASSLIBRARY
TOOBJECT.VRESULT = OEXISTINGOBJECT
RETURN TOOBJECT.VRESULT
ENDIF
CASE EMPTY(TVCLASS)
OOBJECT = TOOBJECT
LCCLASS = LOWER(OOBJECT.CLASS)
LCCLASSLIBRARY = LOWER(OOBJECT.CLASSLIBRARY)
IF  .NOT. ISNULL(OEXISTINGOBJECT) .AND. LOWER(OEXISTINGOBJECT.CLASS)==LCCLASS .AND. LOWER(OEXISTINGOBJECT.CLASSLIBRARY)==LCCLASSLIBRARY
TOOBJECT.VRESULT = OEXISTINGOBJECT
RETURN TOOBJECT.VRESULT
ENDIF
OTHERWISE
LCCLASS = LOWER(ALLTRIM(TVCLASS))
DO CASE
CASE TYPE("tvClassLibrary")=="O"
LCCLASSLIBRARY = LOWER(TVCLASSLIBRARY.CLASSLIBRARY)
CASE TYPE("tvClassLibrary")=="C"
IF EMPTY(TVCLASSLIBRARY)
LCCLASSLIBRARY = LOWER(TOOBJECT.CLASSLIBRARY)
ELSE
LCCLASSLIBRARY = LOWER(ALLTRIM(TVCLASSLIBRARY))
IF EMPTY(JUSTEXT(LCCLASSLIBRARY))
LCCLASSLIBRARY = LOWER(FORCEEXT(LCCLASSLIBRARY, "vcx"))
ENDIF
LLCLASSLIB = (JUSTEXT(LCCLASSLIBRARY)=="vcx")
IF  .NOT. "\"$LCCLASSLIBRARY
LCCLASSLIBRARY = LOWER(FORCEPATH(LCCLASSLIBRARY, JUSTPATH(TOOBJECT.CLASSLIBRARY)))
IF  .NOT. FILE(LCCLASSLIBRARY) .AND. VERSION(2)<>0
LCCLASSLIBRARY = LOWER(FORCEPATH(LCCLASSLIBRARY, HOME()+"ffc\"))
IF  .NOT. FILE(LCCLASSLIBRARY)
LCCLASSLIBRARY = LOWER(FULLPATH(JUSTFNAME(LCCLASSLIBRARY)))
ENDIF
ENDIF
ENDIF
IF  .NOT. FILE(LCCLASSLIBRARY)
TOOBJECT.VRESULT = .NULL.
RETURN TOOBJECT.VRESULT
ENDIF
ENDIF
OTHERWISE
LCCLASSLIBRARY = ""
ENDCASE
IF  .NOT. ISNULL(OEXISTINGOBJECT) .AND. LOWER(OEXISTINGOBJECT.CLASS)==LCCLASS .AND. LOWER(OEXISTINGOBJECT.CLASSLIBRARY)==LCCLASSLIBRARY
TOOBJECT.VRESULT = OEXISTINGOBJECT
RETURN TOOBJECT.VRESULT
ENDIF
OOBJECT = NEWOBJECT(LCCLASS, LCCLASSLIBRARY)
IF TYPE("oObject")<>"O" .OR. ISNULL(OOBJECT)
TOOBJECT.VRESULT = .NULL.
RETURN TOOBJECT.VRESULT
ENDIF
ENDCASE
DO CASE
CASE EMPTY(LCNAME)
TOOBJECT.VRESULT = OOBJECT
RETURN TOOBJECT.VRESULT
OTHERWISE
IF  .NOT. TOOBJECT.ADDPROPERTY(LCNAME, OOBJECT)
OOBJECT = .NULL.
ENDIF
ENDCASE
IF ISNULL(OOBJECT)
TOOBJECT.VRESULT = .NULL.
RETURN TOOBJECT.VRESULT
ENDIF
IF PEMSTATUS(OOBJECT, "oHost", 5)
OOBJECT.OHOST = TOOBJECT.OHOST
ELSE
OOBJECT.ADDPROPERTY("oHost", TOOBJECT.OHOST)
ENDIF
IF EMPTY(LCCLASSLIBRARY)
LCCLASSLIBRARY = LOWER(OOBJECT.CLASSLIBRARY)
ENDIF
LNOBJECTREFCOUNT = TOOBJECT.NOBJECTREFCOUNT
LNOBJECTREFINDEX = LNOBJECTREFCOUNT+1
FOR LNCOUNT = 1 TO LNOBJECTREFCOUNT
IF TOOBJECT.AOBJECTREFS(LNCOUNT, 1)==LOWER(LCNAME)
LNOBJECTREFINDEX = LNCOUNT
EXIT
ENDIF
ENDFOR
IF LNOBJECTREFINDEX>LNOBJECTREFCOUNT
DIMENSION TOOBJECT.AOBJECTREFS[LNOBJECTREFINDEX, 3]
ENDIF
TOOBJECT.AOBJECTREFS[LNOBJECTREFINDEX, 1] = LOWER(LCNAME)
TOOBJECT.AOBJECTREFS[LNOBJECTREFINDEX, 2] = LCCLASS
TOOBJECT.AOBJECTREFS[LNOBJECTREFINDEX, 3] = LCCLASSLIBRARY
TOOBJECT.VRESULT = OOBJECT
RETURN TOOBJECT.VRESULT
ENDFUNC
**
