IF FILE(HOME()+"APP\XinJieAI\AI.APP")
	lcP = SET("Default") + CURDIR()
	TRY
		SET DEFAULT TO HOME()+"APP\XinJieAI\"
		DO AI.APP
		WAIT WINDOW "Start XinJieAI OK" TIMEOUT 3
	CATCH
		
	ENDTRY
	SET DEFAULT TO (lcP)

ENDIF
