**
FUNCTION GKCCheckValidName
LPARAMETERS PCNAME, PCMODE
LOCAL LLVALID, LNNDX, LCNAME
LLVALID = .T.
DO CASE
CASE PCMODE="FILE"
LLVALID = FCHECKFILENAME(PCNAME)
CASE PCMODE="FOLDER"
LLVALID = FCHECKFOLDERNAME(PCNAME)
CASE PCMODE="PATH"
LNNDX = RATC("\", PCNAME, 1)
LCNAME = SUBSTR(PCNAME, LNNDX+1)
LLVALID = FCHECKFILENAME(LCNAME)
IF LLVALID
LCNAME = LEFT(PCNAME, LNNDX-1)
LLVALID = FCHECKFOLDERNAME(LCNAME)
ENDIF
ENDCASE
RETURN LLVALID
ENDFUNC
**
FUNCTION fCheckFileName
LPARAMETERS PCFILENAME
LOCAL LLOK, LNNDX
LLOK = .T.
FOR LNNDX = 1 TO LEN(PCFILENAME)
IF SUBSTR(PCFILENAME, LNNDX, 1)$":/\'*%@!`^%#$~<>?|=" .OR. SUBSTR(PCFILENAME, LNNDX, 1)='"'
LLOK = .F.
EXIT
ENDIF
ENDFOR
RETURN LLOK
ENDFUNC
**
FUNCTION fCheckFolderName
LPARAMETERS PCFOLDERNAME
LOCAL LLOK, LNNDX
LLOK = .T.
FOR LNNDX = 1 TO LEN(PCFOLDERNAME)
IF SUBSTR(PCFOLDERNAME, LNNDX, 1)$"/'*%@!`^%#$~<>?|=" .OR. SUBSTR(PCFOLDERNAME, LNNDX, 1)='"'
LLOK = .F.
EXIT
ENDIF
ENDFOR
RETURN LLOK
ENDFUNC
**
