**
PROCEDURE GKCDebugLog
LPARAMETERS PCOUTPUT
LOCAL LHFILE
IF FILE("GKCDebug.log")
LHFILE = FOPEN("GKCDebug.log", 2)
= FSEEK(LHFILE, 0, 2)
ELSE
LHFILE = FCREATE("GKCDebug.log", 0)
ENDIF
IF LHFILE>0
= FPUTS(LHFILE, PCOUTPUT)
= FCLOSE(LHFILE)
ELSE
= MESSAGEBOX("Unable to open Debug log", 0)
ENDIF
ENDPROC
**
