**
FUNCTION GKCGetCommentStyle
LOCAL LCVERSION, LCREGISTRY, LCCOMMENT
LCVERSION = STR(INT(VAL(LEFT(VERSION(4), 3))), 1)+".0"
LCREGISTRY = "SOFTWARE\Microsoft\VisualFoxPro\"+LCVERSION+"\Options"
LCCOMMENT = GKCGETREGSTRING_HKCU(LCREGISTRY, "EditorCommentString")
IF EMPTY(LCCOMMENT)
LCCOMMENT = "*!*"
ENDIF
RETURN LCCOMMENT
ENDFUNC
**
