**
FUNCTION GKCGetString_VFP
LPARAMETERS PCSUBKEY, PCENTRY
LOCAL LCRETURN, LCALIAS
LCALIAS = ALIAS()
IF GKCGETRESOURCE()
SELECT GKKUSER
LOCATE FOR TYPE='GKCSETTINGS' .AND. ALLTRIM(ID)==UPPER(PCSUBKEY) .AND. ALLTRIM(NAME)==UPPER(PCENTRY) .AND.  .NOT. DELETED()
IF FOUND()
LCRETURN = ALLTRIM(GKKUSER.DATA)
ELSE
LCRETURN = ""
ENDIF
IF  .NOT. EMPTY(LCALIAS)
SELECT (LCALIAS)
ENDIF
ELSE
LCRETURN = ""
ENDIF
RETURN LCRETURN
ENDFUNC
**
