**
FUNCTION GKCGetFileNamePath
LPARAMETERS TOFORM, TOCODEMAX, TCTYPE, TCSTEMNAME, TCFILEEXT
LOCAL LCFULLNAME, LCPROJFILE, LOEXCEPTION, LCERRMSG, LNFILECNT, LCBASEPATH, LNNUMFLDRS, LNFLDR
LOCAL LAFILE[1, 5], LAFLDLIST[1, 5]
LCFULLNAME = ""
IF  .NOT. ISNULL(TOFORM.PROJECTDOCK)
	LCPROJFILE = TOFORM.PROJECTDOCK.PROJECTNAME
	TRY
		USE (LCPROJFILE) AGAIN ALIAS GKCPJX IN 0
		SELECT GKCPJX
		LOCATE FOR TYPE=TCTYPE .AND. ALLTRIM(KEY)==UPPER(TCSTEMNAME)
		IF FOUND()
			LCFULLNAME = GKCGETFILEFULLPATH(GKCPJX.NAME, TOFORM.PROJECTDOCK.BASEPATH)
		ENDIF
		USE
	CATCH TO LOEXCEPTION
	ENDTRY
ENDIF
IF EMPTY(LCFULLNAME)
	DO CASE
		CASE PEMSTATUS(TOFORM, "BasePath", 5) .AND.  .NOT. EMPTY(TOFORM.BASEPATH)
			LCTESTNAME = ADDBS(TOFORM.BASEPATH)+TCSTEMNAME+"."+TCFILEEXT
			LNFILECNT = ADIR(LAFILE, LCTESTNAME)
			IF LNFILECNT=0
				LCBASEPATH = LEFT(TOFORM.BASEPATH, RATC("\", ADDBS(TOFORM.BASEPATH), 2))
				LNNUMFLDRS = ADIR(LAFLDLIST, LCBASEPATH+"*.*", "D")
				FOR LNFLDR = 1 TO LNNUMFLDRS
					IF LAFLDLIST(LNFLDR, 1)<>"." .AND. ATC("D", LAFLDLIST(LNFLDR, 5))>0
						LCTESTNAME = ADDBS(LCBASEPATH+LAFLDLIST(LNFLDR, 1))+TCSTEMNAME+"."+TCFILEEXT
						LNFILECNT = ADIR(LAFILE, LCTESTNAME)
						IF LNFILECNT>0
							LCFULLNAME = LOWER(LCTESTNAME)
							EXIT
						ENDIF
					ENDIF
				ENDFOR
			ELSE
				LCFULLNAME = LOWER(LCTESTNAME)
			ENDIF
		CASE PEMSTATUS(TOCODEMAX, "BasePath", 5) .AND.  .NOT. EMPTY(TOCODEMAX.BASEPATH)
			LCTESTNAME = ADDBS(TOCODEMAX.BASEPATH)+TCSTEMNAME+"."+TCFILEEXT
			LNFILECNT = ADIR(LAFILE, LCTESTNAME)
			IF LNFILECNT=0
				LCBASEPATH = LEFT(TOCODEMAX.BASEPATH, RATC("\", ADDBS(TOCODEMAX.BASEPATH), 2))
				LNNUMFLDRS = ADIR(LAFLDLIST, LCBASEPATH+"*.*", "D")
				FOR LNFLDR = 1 TO LNNUMFLDRS
					IF LAFLDLIST(LNFLDR, 1)<>"." .AND. ATC("D", LAFLDLIST(LNFLDR, 5))>0
						LCTESTNAME = ADDBS(LCBASEPATH+LAFLDLIST(LNFLDR, 1))+TCSTEMNAME+"."+TCFILEEXT
						LNFILECNT = ADIR(LAFILE, LCTESTNAME)
						IF LNFILECNT>0
							LCFULLNAME = LOWER(LCTESTNAME)
							EXIT
						ENDIF
					ENDIF
				ENDFOR
			ELSE
				LCFULLNAME = LOWER(LCTESTNAME)
			ENDIF
	ENDCASE
ENDIF
RETURN LCFULLNAME
ENDFUNC