**
FUNCTION GKCGetRegString_HKCU
LPARAMETERS TCSUBKEY, TCENTRY
LOCAL LNREGHANDLE, LNRESULT, LNSIZE, LCDATABUFFER, TNTYPE
LNREGHANDLE = 0
LNRESULT = REGOPENKEY(-2147483647, TCSUBKEY, @LNREGHANDLE)
IF LNRESULT<>0
RETURN ""
ENDIF
LCDATABUFFER = SPACE(2000)
LNSIZE = LEN(LCDATABUFFER)
LNTYPE = 0
LNRESULT = REGQUERYVALUEEX(LNREGHANDLE, TCENTRY, 0, @LNTYPE, @LCDATABUFFER, @LNSIZE)
= REGCLOSEKEY(LNREGHANDLE)
IF LNRESULT<>0
RETURN ""
ENDIF
IF LNSIZE<2
RETURN ""
ENDIF
RETURN SUBSTR(LCDATABUFFER, 1, LNSIZE-1)
ENDFUNC
**
