**
FUNCTION GKCPixelsToTwips
LPARAMETERS PNPIXELS, PCDIRECTION
LOCAL LHDEVICEHDL, LNPIXELSPERINCH
LHDEVICEHDL = GETDC(0)
DO CASE
CASE PCDIRECTION="H"
LNPIXELSPERINCH = GETDEVICECAPS(LHDEVICEHDL, 88)
CASE PCDIRECTION="V"
LNPIXELSPERINCH = GETDEVICECAPS(LHDEVICEHDL, 90)
ENDCASE
LHDEVICEHDL = RELEASEDC(0, LHDEVICEHDL)
RETURN PNPIXELS*1440/LNPIXELSPERINCH
ENDFUNC
**
