**
FUNCTION GKCTwipsToPixels
LPARAMETERS PNTWIPS, PCDIRECTION
LOCAL LHDEVICEHDL, LNPIXELSPERINCH
LHDEVICEHDL = GETDC(0)
DO CASE
CASE PCDIRECTION="H"
LNPIXELSPERINCH = GETDEVICECAPS(LHDEVICEHDL, 88)
CASE PCDIRECTION="V"
LNPIXELSPERINCH = GETDEVICECAPS(LHDEVICEHDL, 90)
ENDCASE
LHDEVICEHDL = RELEASEDC(0, LHDEVICEHDL)
RETURN PNTWIPS/1440*LNPIXELSPERINCH
ENDFUNC
**
