FUNCTION SHGetSpecialFolderPath
	LPARAMETERS hwndOwner, lpszPath, nFolder, ifCreate
	DECLARE INTEGER SHGetSpecialFolderPath IN Shell32.DLL INTEGER hwndOwner, STRING @lpszPath, INTEGER nFolder, INTEGER ifCreate
	RETURN SHGetSpecialFolderPath(m.hwndOwner, @m.lpszPath, m.nFolder, m.ifCreate)
ENDFUNC

**

FUNCTION RtlS2PL
LPARAMETERS tnDest, tcSrc, tnLen
DECLARE RtlMoveMemory IN WIN32API AS RtlS2PL Long @Dest, String Source, Long Length
RETURN RtlS2PL(@tnDest, @tcSrc, tnLen) 
ENDFUNC

**

FUNCTION SetFileAttributes
LPARAMETERS tcFileName, tnFileAttributes
DECLARE LONG SetFileAttributes IN WIN32API STRING tcFileName, LONG tnFileAttributes
RETURN SetFileAttributes(tcFileName, tnFileAttributes)
ENDFUNC

**

FUNCTION GetFileAttributes
LPARAMETERS tcFileName
DECLARE LONG GetFileAttributes IN WIN32API STRING tcFileName
RETURN GetFileAttributes(tcFileName)
ENDFUNC

**
FUNCTION CopyFile
LPARAMETERS TCSOURCEFILENAME, TCDESTFILENAME, TLFAILIFEXISTS
DECLARE LONG CopyFile IN Win32API STRING, STRING, LONG
RETURN COPYFILE(TCSOURCEFILENAME, TCDESTFILENAME, TLFAILIFEXISTS)
ENDFUNC
**
FUNCTION MoveFile
LPARAMETERS TCSOURCEFILENAME, TCDESTFILENAME
DECLARE LONG MoveFile IN Win32API STRING, STRING
RETURN MOVEFILE(TCSOURCEFILENAME, TCDESTFILENAME)
ENDFUNC
**
FUNCTION DocumentProperties
LPARAMETERS LHWND, LHPRINTER, PCPRINTERNAME, LCDEVMODEOUTPUT, LCDEVMODEINPUT, LNMODE
DECLARE INTEGER DocumentProperties IN winspool.drv INTEGER, INTEGER, STRING, STRING @, STRING @, INTEGER
RETURN DOCUMENTPROPERTIES(LHWND, LHPRINTER, PCPRINTERNAME, @LCDEVMODEOUTPUT, @LCDEVMODEINPUT, LNMODE)
ENDFUNC
**
FUNCTION ClosePrinter
LPARAMETERS LHPRINTER
DECLARE INTEGER ClosePrinter IN winspool.drv INTEGER
RETURN CLOSEPRINTER(LHPRINTER)
ENDFUNC
**
FUNCTION OpenPrinter
LPARAMETERS PCPRINTERNAME, LHPRINTER, LNDEFAULT
DECLARE INTEGER OpenPrinter IN winspool.drv STRING, INTEGER @, INTEGER
RETURN OPENPRINTER(PCPRINTERNAME, @LHPRINTER, LNDEFAULT)
ENDFUNC
**
FUNCTION StartDoc
LPARAMETERS HDC, LPDI
DECLARE INTEGER StartDoc IN Win32API INTEGER, STRING
RETURN STARTDOC(HDC, LPDI)
ENDFUNC
**
FUNCTION EndDoc
LPARAMETERS HDC
DECLARE INTEGER EndDoc IN Win32API INTEGER
RETURN ENDDOC(HDC)
ENDFUNC
**
FUNCTION EndPage
LPARAMETERS HDC
DECLARE INTEGER EndPage IN Win32API INTEGER
RETURN ENDPAGE(HDC)
ENDFUNC
**
FUNCTION StartPage
LPARAMETERS HDC
DECLARE INTEGER StartPage IN Win32API INTEGER
RETURN STARTPAGE(HDC)
ENDFUNC
**
FUNCTION AbortDoc
LPARAMETERS HDC
DECLARE INTEGER AbortDoc IN Win32API INTEGER
RETURN ABORTDOC(HDC)
ENDFUNC
**
FUNCTION CoCreateGuid
LPARAMETERS TPGUID
DECLARE INTEGER CoCreateGuid IN 'OLE32.dll' STRING @
RETURN COCREATEGUID(@TPGUID)
ENDFUNC
**
FUNCTION StringFromGUID2
LPARAMETERS TRGUID, TPSZ, TCHMAX
DECLARE INTEGER StringFromGUID2 IN 'OLE32.dll' STRING, STRING @, INTEGER
RETURN STRINGFROMGUID2(TRGUID, @TPSZ, TCHMAX)
ENDFUNC
**
FUNCTION UuidCreateSequential
LPARAMETERS TUUID
DECLARE INTEGER UuidCreateSequential IN 'RPCRT4.dll' STRING @
RETURN UUIDCREATESEQUENTIAL(@TUUID)
ENDFUNC
**
FUNCTION UuidFromString
LPARAMETERS TSSTRINGUUID, TSGUID
DECLARE LONG UuidFromString IN rpcrt4.DLL STRING, STRING @
RETURN UUIDFROMSTRING(TSSTRINGUUID, @TSGUID)
ENDFUNC
**
FUNCTION GdiplusStartup
LPARAMETERS TNTOKEN, PCINPUT, TNOUTPUT
DECLARE LONG GdiplusStartup IN GDIPLUS.DLL LONG @, STRING @, LONG @
RETURN GDIPLUSSTARTUP(@TNTOKEN, @PCINPUT, @TNOUTPUT)
ENDFUNC
**
FUNCTION GdiplusShutdown
LPARAMETERS TNTOKEN
DECLARE LONG GdiplusShutdown IN GDIPLUS.DLL LONG
RETURN GDIPLUSSHUTDOWN(TNTOKEN)
ENDFUNC
**
FUNCTION GdipGetImageGraphicsContext
LPARAMETERS TNIMAGE, TNGRAPHICS
DECLARE INTEGER GdipGetImageGraphicsContext IN GDIPLUS.DLL INTEGER, INTEGER @
RETURN GDIPGETIMAGEGRAPHICSCONTEXT(TNIMAGE, @TNGRAPHICS)
ENDFUNC
**
FUNCTION GdipDeleteGraphics
LPARAMETERS TNIMAGE
DECLARE INTEGER GdipDeleteGraphics IN GDIPLUS.DLL INTEGER
RETURN GDIPDELETEGRAPHICS(TNIMAGE)
ENDFUNC
**
FUNCTION GdipSetTextRenderingHint
LPARAMETERS TNGRAPHICS, TNTEXTRENDERINGHINT
DECLARE INTEGER GdipSetTextRenderingHint IN GDIPLUS.DLL INTEGER, INTEGER
RETURN GDIPSETTEXTRENDERINGHINT(TNGRAPHICS, TNTEXTRENDERINGHINT)
ENDFUNC
**
FUNCTION GdipMeasureString
LPARAMETERS TNGRAPHICS, PCUNICODE, TNLENGTH, TNFONT, PCLAYOUTRECT, TNSTRINGFORMAT, PCRECTOUT, TNCHARS, TNLINES
DECLARE INTEGER GdipMeasureString IN GDIPLUS.DLL INTEGER, STRING, INTEGER, INTEGER, STRING, INTEGER, STRING @, INTEGER @, INTEGER @
RETURN GDIPMEASURESTRING(TNGRAPHICS, PCUNICODE, TNLENGTH, TNFONT, PCLAYOUTRECT, TNSTRINGFORMAT, @PCRECTOUT, @TNCHARS, @TNLINES)
ENDFUNC
**
FUNCTION GdipDrawString
LPARAMETERS TNGRAPHICS, TCWIDECHAR, TNLENGTH, TNFNT, TCRECTF, TNSTRINGFORMAT, TNBRUSH
DECLARE INTEGER GdipDrawString IN GDIPLUS.DLL INTEGER, STRING, INTEGER, INTEGER, STRING @, INTEGER, INTEGER
RETURN GDIPDRAWSTRING(TNGRAPHICS, TCWIDECHAR, TNLENGTH, TNFNT, @TCRECTF, TNSTRINGFORMAT, TNBRUSH)
ENDFUNC
**
FUNCTION GdipDrawImageRectRect
LPARAMETERS TNGRAPHICS, TNIMAGE, TNDSTX, TNDSTY, TNDSTWIDTH, TNDSTHEIGHT, TNSRCX, TNSRCY, TNSRCWIDTH, TNSRCHEIGHT, TNSRCUNIT, TNIMAGEATTRIBUTES, TNCALLBACK, TNCALLBACKDATA
DECLARE INTEGER GdipDrawImageRectRect IN GDIPLUS.DLL INTEGER, INTEGER, SINGLE, SINGLE, SINGLE, SINGLE, SINGLE, SINGLE, SINGLE, SINGLE, INTEGER, INTEGER, INTEGER, INTEGER
RETURN GDIPDRAWIMAGERECTRECT(TNGRAPHICS, TNIMAGE, TNDSTX, TNDSTY, TNDSTWIDTH, TNDSTHEIGHT, TNSRCX, TNSRCY, TNSRCWIDTH, TNSRCHEIGHT, TNSRCUNIT, TNIMAGEATTRIBUTES, TNCALLBACK, TNCALLBACKDATA)
ENDFUNC
**
FUNCTION GdipDrawImage
LPARAMETERS TNGRAPHICS, TNIMAGE, TNX, TNY
DECLARE INTEGER GdipDrawImage IN GDIPLUS.DLL INTEGER, INTEGER, SINGLE, SINGLE
RETURN GDIPDRAWIMAGE(TNGRAPHICS, TNIMAGE, TNX, TNY)
ENDFUNC
**
FUNCTION GdipFillRectangle
LPARAMETERS TNGRAPHICS, TNBRUSH, TNX, TNY, TNWIDTH, TNHEIGHT
DECLARE INTEGER GdipFillRectangle IN GDIPLUS.DLL INTEGER, INTEGER, SINGLE, SINGLE, SINGLE, SINGLE
RETURN GDIPFILLRECTANGLE(TNGRAPHICS, TNBRUSH, TNX, TNY, TNWIDTH, TNHEIGHT)
ENDFUNC
**
FUNCTION GdipDrawImageRect
LPARAMETERS TNGRAPHICS, TNIMAGE, TNX, TNY, TNIMGWIDTH, TNIMGHEIGHT
DECLARE INTEGER GdipDrawImageRect IN GDIPLUS.DLL INTEGER, INTEGER, SINGLE, SINGLE, SINGLE, SINGLE
RETURN GDIPDRAWIMAGERECT(TNGRAPHICS, TNIMAGE, TNX, TNY, TNIMGWIDTH, TNIMGHEIGHT)
ENDFUNC
**
FUNCTION GdipCreateBitmapFromScan0
LPARAMETERS TNWIDTH, TNHEIGHT, TNSTRIDE, TNPIXELFORMAT, TNSCAN0, TNIMAGE
DECLARE INTEGER GdipCreateBitmapFromScan0 IN GDIPLUS.DLL INTEGER, INTEGER, INTEGER, INTEGER, INTEGER, INTEGER @
RETURN GDIPCREATEBITMAPFROMSCAN0(TNWIDTH, TNHEIGHT, TNSTRIDE, TNPIXELFORMAT, TNSCAN0, @TNIMAGE)
ENDFUNC
**
FUNCTION GdipLoadImageFromFile
LPARAMETERS PCFILENAME, TNIMAGE
DECLARE INTEGER GdipLoadImageFromFile IN GDIPLUS.DLL STRING, INTEGER @
RETURN GDIPLOADIMAGEFROMFILE(PCFILENAME, @TNIMAGE)
ENDFUNC
**
FUNCTION GdipSaveImageToFile
LPARAMETERS TNIMAGE, PCFILENAME, PCCLSIDENCODER, TNENCODERPARAMS
DECLARE LONG GdipSaveImageToFile IN GDIPLUS.DLL LONG, STRING, STRING, LONG
RETURN GDIPSAVEIMAGETOFILE(TNIMAGE, PCFILENAME, PCCLSIDENCODER, TNENCODERPARAMS)
ENDFUNC
**
FUNCTION GdipDisposeImage
LPARAMETERS TNIMAGE
DECLARE INTEGER GdipDisposeImage IN GDIPLUS.DLL INTEGER
RETURN GDIPDISPOSEIMAGE(TNIMAGE)
ENDFUNC
**
FUNCTION GdipBitmapGetPixel
LPARAMETERS TNBITMAP, TNX, TNY, TNARGB
DECLARE INTEGER GdipBitmapGetPixel IN GDIPLUS.DLL INTEGER, INTEGER, INTEGER, INTEGER @
RETURN GDIPBITMAPGETPIXEL(TNBITMAP, TNX, TNY, @TNARGB)
ENDFUNC
**
FUNCTION GdipGetImageWidth
LPARAMETERS TNIMAGE, TNWIDTH
DECLARE INTEGER GdipGetImageWidth IN GDIPLUS.DLL INTEGER, INTEGER @
RETURN GDIPGETIMAGEWIDTH(TNIMAGE, @TNWIDTH)
ENDFUNC
**
FUNCTION GdipGetImageHeight
LPARAMETERS TNIMAGE, TNHEIGHT
DECLARE INTEGER GdipGetImageHeight IN GDIPLUS.DLL INTEGER, INTEGER @
RETURN GDIPGETIMAGEHEIGHT(TNIMAGE, @TNHEIGHT)
ENDFUNC
**
FUNCTION GdipCreateImageAttributes
LPARAMETERS TNIMAGEATTR
DECLARE INTEGER GdipCreateImageAttributes IN GDIPLUS.DLL INTEGER @
RETURN GDIPCREATEIMAGEATTRIBUTES(@TNIMAGEATTR)
ENDFUNC
**
FUNCTION GdipSetImageAttributesRemapTable
LPARAMETERS TNIMAGEATTR, TNCOLORADJUSTTYPE, TNENABLEFLAG, TNMAPSIZE, PCCOLORMAP
DECLARE INTEGER GdipSetImageAttributesRemapTable IN GDIPLUS.DLL INTEGER, INTEGER, INTEGER, INTEGER, STRING
RETURN GDIPSETIMAGEATTRIBUTESREMAPTABLE(TNIMAGEATTR, TNCOLORADJUSTTYPE, TNENABLEFLAG, TNMAPSIZE, PCCOLORMAP)
ENDFUNC
**
FUNCTION GdipSetImageAttributesColorMatrix
LPARAMETERS TNIMAGEATTR, TNTYPE, TNENABLEFLAG, PCCOLORMATRIX, TNGRAYMATRIX, TNFLAGS
DECLARE LONG GdipSetImageAttributesColorMatrix IN GDIPLUS.DLL LONG, LONG, LONG, STRING, LONG, LONG
RETURN GDIPSETIMAGEATTRIBUTESCOLORMATRIX(TNIMAGEATTR, TNTYPE, TNENABLEFLAG, PCCOLORMATRIX, TNGRAYMATRIX, TNFLAGS)
ENDFUNC
**
FUNCTION GdipDisposeImageAttributes
LPARAMETERS TNIMAGEATTR
DECLARE INTEGER GdipDisposeImageAttributes IN GDIPLUS.DLL INTEGER
RETURN GDIPDISPOSEIMAGEATTRIBUTES(TNIMAGEATTR)
ENDFUNC
**
FUNCTION GdipCreateStringFormat
LPARAMETERS TNFORMATATTRIBUTES, TNLANGUAGE, TNFMT
DECLARE INTEGER GdipCreateStringFormat IN GDIPLUS.DLL INTEGER, INTEGER, INTEGER @
RETURN GDIPCREATESTRINGFORMAT(TNFORMATATTRIBUTES, TNLANGUAGE, @TNFMT)
ENDFUNC
**
FUNCTION GdipDeleteStringFormat
LPARAMETERS TNSTRINGFORMAT
DECLARE INTEGER GdipDeleteStringFormat IN GDIPLUS.DLL INTEGER
RETURN GDIPDELETESTRINGFORMAT(TNSTRINGFORMAT)
ENDFUNC
**
FUNCTION GdipSetStringFormatHotkeyPrefix
LPARAMETERS TNGRAPHICS, TNHOTKEYPREFIX
DECLARE INTEGER GdipSetStringFormatHotkeyPrefix IN GDIPLUS.DLL INTEGER, INTEGER
RETURN GDIPSETSTRINGFORMATHOTKEYPREFIX(TNGRAPHICS, TNHOTKEYPREFIX)
ENDFUNC
**
FUNCTION GdipStringFormatGetGenericTypographic
LPARAMETERS TNHANDLE
DECLARE INTEGER GdipStringFormatGetGenericTypographic IN GDIPLUS.DLL INTEGER @
RETURN GDIPSTRINGFORMATGETGENERICTYPOGRAPHIC(@TNHANDLE)
ENDFUNC
**
FUNCTION GdipCreateFont
LPARAMETERS TNFONTFAMILY, TNEMSIZE, TNFONTSTYLE, TNUNIT, TNFONT
DECLARE INTEGER GdipCreateFont IN GDIPLUS.DLL INTEGER, SINGLE, INTEGER, INTEGER, INTEGER @
RETURN GDIPCREATEFONT(TNFONTFAMILY, TNEMSIZE, TNFONTSTYLE, TNUNIT, @TNFONT)
ENDFUNC
**
FUNCTION GdipCreateFontFamilyFromName
LPARAMETERS PCFAMILYNAME, TNFONTCOLLECTION, TNFONTFAMILY
DECLARE INTEGER GdipCreateFontFamilyFromName IN GDIPLUS.DLL STRING, INTEGER, INTEGER @
RETURN GDIPCREATEFONTFAMILYFROMNAME(PCFAMILYNAME, TNFONTCOLLECTION, @TNFONTFAMILY)
ENDFUNC
**
FUNCTION GdipDeleteFont
LPARAMETERS TNFONT
DECLARE INTEGER GdipDeleteFont IN GDIPLUS.DLL INTEGER
RETURN GDIPDELETEFONT(TNFONT)
ENDFUNC
**
FUNCTION GdipDeleteFontFamily
LPARAMETERS TNFONTFAMILY
DECLARE INTEGER GdipDeleteFontFamily IN GDIPLUS.DLL INTEGER
RETURN GDIPDELETEFONTFAMILY(TNFONTFAMILY)
ENDFUNC
**
FUNCTION GdipCreateSolidFill
LPARAMETERS TNCOLOR, TNBRUSH
DECLARE INTEGER GdipCreateSolidFill IN GDIPLUS.DLL INTEGER, INTEGER @
RETURN GDIPCREATESOLIDFILL(TNCOLOR, @TNBRUSH)
ENDFUNC
**
FUNCTION GdipCreateLineBrushI
LPARAMETERS PCPOINT1, PCPOINT2, TNCOLOR1, TNCOLOR2, TNMODE, TNWRAPMODE, TNLINEGRADIENT
DECLARE LONG GdipCreateLineBrushI IN GDIPLUS.DLL STRING, STRING, LONG, LONG, LONG, LONG, LONG @
RETURN GDIPCREATELINEBRUSHI(PCPOINT1, PCPOINT2, TNCOLOR1, TNCOLOR2, TNMODE, TNWRAPMODE, @TNLINEGRADIENT)
ENDFUNC
**
FUNCTION GdipCreateLineBrushFromRect
LPARAMETERS TNRECT, TNCOLOR1, TNCOLOR2, TNMODE, TNWRAPMD, TNLINEGRADIENT
DECLARE LONG GdipCreateLineBrushFromRect IN GDIPLUS.DLL STRING @, LONG, LONG, LONG, LONG, LONG @
RETURN GDIPCREATELINEBRUSHFROMRECT(@TNRECT, TNCOLOR1, TNCOLOR2, TNMODE, TNWRAPMD, @TNLINEGRADIENT)
ENDFUNC
**
FUNCTION GdipCreateLineBrushFromRectI
LPARAMETERS TNRECT, TNCOLOR1, TNCOLOR2, TNMODE, TNWRAPMODE, TNLINEGRADIENT
DECLARE LONG GdipCreateLineBrushFromRectI IN GDIPLUS.DLL STRING @, LONG, LONG, LONG, LONG, LONG @
RETURN GDIPCREATELINEBRUSHFROMRECTI(@TNRECT, TNCOLOR1, TNCOLOR2, TNMODE, TNWRAPMODE, @TNLINEGRADIENT)
ENDFUNC
**
FUNCTION GdipSetLinePresetBlend
LPARAMETERS TNBRUSH, TNBLEND, PCPOSITIONS, TNCOUNT
DECLARE LONG GdipSetLinePresetBlend IN GDIPLUS.DLL LONG, STRING, STRING, LONG
RETURN GDIPSETLINEPRESETBLEND(TNBRUSH, TNBLEND, PCPOSITIONS, TNCOUNT)
ENDFUNC
**
FUNCTION GdipDeleteBrush
LPARAMETERS TNBRUSH
DECLARE INTEGER GdipDeleteBrush IN GDIPLUS.DLL INTEGER
RETURN GDIPDELETEBRUSH(TNBRUSH)
ENDFUNC
**
FUNCTION GdipCreatePath
LPARAMETERS TNBRUSHMODE, TNPATH
DECLARE LONG GdipCreatePath IN GDIPLUS.DLL LONG, LONG @
RETURN GDIPCREATEPATH(TNBRUSHMODE, @TNPATH)
ENDFUNC
**
FUNCTION GdipAddPathRectangle
LPARAMETERS TNPATH, TNX, TNY, TNWIDTH, TNHEIGHT
DECLARE LONG GdipAddPathRectangle IN GDIPLUS.DLL LONG, SINGLE, SINGLE, SINGLE, SINGLE
RETURN GDIPADDPATHRECTANGLE(TNPATH, TNX, TNY, TNWIDTH, TNHEIGHT)
ENDFUNC
**
FUNCTION GdipCreatePathGradientFromPath
LPARAMETERS TNPATH, TNPOLYGRADIENT
DECLARE LONG GdipCreatePathGradientFromPath IN GDIPLUS.DLL LONG, LONG @
RETURN GDIPCREATEPATHGRADIENTFROMPATH(TNPATH, @TNPOLYGRADIENT)
ENDFUNC
**
FUNCTION GdipSetPathGradientCenterColor
LPARAMETERS TNBRUSH, TNCOLORS
DECLARE LONG GdipSetPathGradientCenterColor IN GDIPLUS.DLL LONG, LONG
RETURN GDIPSETPATHGRADIENTCENTERCOLOR(TNBRUSH, TNCOLORS)
ENDFUNC
**
FUNCTION GdipSetPathGradientSurroundColorsWithCount
LPARAMETERS TNBRUSH, TNARGB, TNCOUNT
DECLARE LONG GdipSetPathGradientSurroundColorsWithCount IN GDIPLUS.DLL LONG, LONG @, LONG @
RETURN GDIPSETPATHGRADIENTSURROUNDCOLORSWITHCOUNT(TNBRUSH, @TNARGB, @TNCOUNT)
ENDFUNC
**
FUNCTION GdipDeletePath
LPARAMETERS TNPATH
DECLARE LONG GdipDeletePath IN GDIPLUS.DLL LONG
RETURN GDIPDELETEPATH(TNPATH)
ENDFUNC
**
FUNCTION CreateMenu
DECLARE LONG CreateMenu IN User32
RETURN CREATEMENU()
ENDFUNC
**
FUNCTION DrawMenuBar
LPARAMETERS THWNDMENU
DECLARE LONG DrawMenuBar IN User32 LONG
RETURN DRAWMENUBAR(THWNDMENU)
ENDFUNC
**
FUNCTION GetMenu
LPARAMETERS THWNDMENU
DECLARE LONG GetMenu IN User32 LONG
RETURN GETMENU(THWNDMENU)
ENDFUNC
**
FUNCTION GetSystemMenu
LPARAMETERS THWNDMAIN, TBREVERT
DECLARE LONG GetSystemMenu IN User32 LONG, LONG
RETURN GETSYSTEMMENU(THWNDMAIN, TBREVERT)
ENDFUNC
**
FUNCTION SetMenu
LPARAMETERS THWNDMENU, THMENU
DECLARE LONG SetMenu IN User32 LONG, LONG
RETURN SETMENU(THWNDMENU, THMENU)
ENDFUNC
**
FUNCTION CreatePopupMenu
DECLARE LONG CreatePopupMenu IN User32
RETURN CREATEPOPUPMENU()
ENDFUNC
**
FUNCTION IsMenu
LPARAMETERS THMENU
DECLARE LONG IsMenu IN User32 LONG
RETURN ISMENU(THMENU)
ENDFUNC
**
FUNCTION DestroyMenu
LPARAMETERS THMENU
DECLARE LONG DestroyMenu IN User32 LONG
RETURN DESTROYMENU(THMENU)
ENDFUNC
**
FUNCTION AppendMenu
LPARAMETERS THMENU, TUFLAGS, TUIDNEWITEM, TLPNEWITEM
DECLARE LONG AppendMenu IN User32 LONG, LONG, LONG, LONG
RETURN APPENDMENU(THMENU, TUFLAGS, TUIDNEWITEM, TLPNEWITEM)
ENDFUNC
**
FUNCTION ModifyMenu
LPARAMETERS THMENU, TNPOSID, TNFLAGS, TNNEWID, TLPNEWID
DECLARE SHORT ModifyMenu IN User32 LONG, LONG, LONG, LONG, STRING
RETURN MODIFYMENU(THMENU, TNPOSID, TNFLAGS, TNNEWID, TLPNEWID)
ENDFUNC
**
FUNCTION EnableMenuItem
LPARAMETERS THMENU, TNITEMID, TNFLAGS
DECLARE LONG EnableMenuItem IN User32 LONG, LONG, LONG
RETURN ENABLEMENUITEM(THMENU, TNITEMID, TNFLAGS)
ENDFUNC
**
FUNCTION GetMenuInfo
LPARAMETERS THMENU, TLPCMI
DECLARE LONG GetMenuInfo IN User32 LONG, STRING @
RETURN GETMENUINFO(THMENU, @TLPCMI)
ENDFUNC
**
FUNCTION SetMenuInfo
LPARAMETERS THMENU, TLPCMI
DECLARE LONG SetMenuInfo IN User32 LONG, STRING @
RETURN SETMENUINFO(THMENU, @TLPCMI)
ENDFUNC
**
FUNCTION GetMenuBarInfo
LPARAMETERS TNHWND, TIDOBJECT, TIDITEM, TLPMBI
DECLARE LONG GetMenuBarInfo IN User32 LONG, LONG, LONG, STRING @
RETURN GETMENUBARINFO(TNHWND, TIDOBJECT, TIDITEM, @TLPMBI)
ENDFUNC
**
FUNCTION GetMenuString
LPARAMETERS THMENU, TUIDITEM, TLPSTRING, TNMAXCOUNT, TUFLAG
DECLARE INTEGER GetMenuString IN User32 LONG, LONG, STRING @, INTEGER, LONG
RETURN GETMENUSTRING(THMENU, TUIDITEM, @TLPSTRING, TNMAXCOUNT, TUFLAG)
ENDFUNC
**
FUNCTION GetMenuItemRect
LPARAMETERS THWNDMENU, THMENU, TNITEM, TLPITEMRECT
DECLARE SHORT GetMenuItemRect IN User32 LONG, LONG, LONG, STRING @
RETURN GETMENUITEMRECT(THWNDMENU, THMENU, TNITEM, @TLPITEMRECT)
ENDFUNC
**
FUNCTION GetMenuItemCount
LPARAMETERS THMENU
DECLARE INTEGER GetMenuItemCount IN User32 LONG
RETURN GETMENUITEMCOUNT(THMENU)
ENDFUNC
**
FUNCTION GetMenuItemID
LPARAMETERS THMENU, TNPOSID
DECLARE LONG GetMenuItemID IN User32 LONG, LONG
RETURN GETMENUITEMID(THMENU, TNPOSID)
ENDFUNC
**
FUNCTION GetMenuItemInfo
LPARAMETERS THMENU, TUITEM, TFBYPOSITION, TLPMII
DECLARE LONG GetMenuItemInfo IN User32 LONG, LONG, LONG, STRING @
RETURN GETMENUITEMINFO(THMENU, TUITEM, TFBYPOSITION, @TLPMII)
ENDFUNC
**
FUNCTION SetMenuItemInfo
LPARAMETERS THMENU, TUITEM, TFBYPOSITION, TLPMII
DECLARE SHORT SetMenuItemInfo IN User32 LONG, LONG, LONG, STRING
RETURN SETMENUITEMINFO(THMENU, TUITEM, TFBYPOSITION, TLPMII)
ENDFUNC
**
FUNCTION MenuItemFromPoint
LPARAMETERS TNHWND, THMENU, TNX, TNY
DECLARE INTEGER MenuItemFromPoint IN User32 LONG, LONG, LONG, LONG
RETURN MENUITEMFROMPOINT(TNHWND, THMENU, TNX, TNY)
ENDFUNC
**
FUNCTION GetMenuPosFromID
LPARAMETERS THMENU, TNID
DECLARE LONG GetMenuPosFromID IN ShlwApi LONG, LONG
RETURN GETMENUPOSFROMID(THMENU, TNID)
ENDFUNC
**
FUNCTION TrackPopupMenu
LPARAMETERS THMENU, TUFLAGS, TNX, TNY, TNRESERVED, TNHWND, TPRCRECT
DECLARE LONG TrackPopupMenu IN User32 LONG, LONG, INTEGER, INTEGER, INTEGER, LONG, LONG
RETURN TRACKPOPUPMENU(THMENU, TUFLAGS, TNX, TNY, TNRESERVED, TNHWND, TPRCRECT)
ENDFUNC
**
FUNCTION LoadImage
LPARAMETERS THINST, TLPSZNAME, TUTYPE, TCXDESIRED, TCYDESIRED, TFULOAD
DECLARE LONG LoadImage IN User32 LONG, STRING, LONG, INTEGER, INTEGER, LONG
RETURN LOADIMAGE(THINST, TLPSZNAME, TUTYPE, TCXDESIRED, TCYDESIRED, TFULOAD)
ENDFUNC
**
FUNCTION GetCursorPos
LPARAMETERS TLPPOINT
DECLARE LONG GetCursorPos IN User32 STRING @
RETURN GETCURSORPOS(TLPPOINT)
ENDFUNC
**
FUNCTION GetClientRect
LPARAMETERS TNHWND, TLPRECT
DECLARE LONG GetClientRect IN User32 LONG, STRING @
RETURN GETCLIENTRECT(TNHWND, @TLPRECT)
ENDFUNC
**
FUNCTION GetDC
LPARAMETERS TNHWND
DECLARE LONG GetDC IN User32 LONG
RETURN GETDC(TNHWND)
ENDFUNC
**
FUNCTION CreateCompatibleDC
LPARAMETERS THDC
DECLARE LONG CreateCompatibleDC IN GDI32 LONG
RETURN CREATECOMPATIBLEDC(THDC)
ENDFUNC
**
FUNCTION CreateCompatibleBitmap
LPARAMETERS THDC, TNWIDTH, TNHEIGHT
DECLARE LONG CreateCompatibleBitmap IN GDI32 LONG, LONG, LONG
RETURN CREATECOMPATIBLEBITMAP(THDC, TNWIDTH, TNHEIGHT)
ENDFUNC
**
FUNCTION SelectObject
LPARAMETERS THDC, THOBJECT
DECLARE LONG SelectObject IN GDI32 LONG, LONG
RETURN SELECTOBJECT(THDC, THOBJECT)
ENDFUNC
**
FUNCTION ReleaseDC
LPARAMETERS TNHWND, THDC
DECLARE INTEGER ReleaseDC IN User32 LONG, LONG
RETURN RELEASEDC(TNHWND, THDC)
ENDFUNC
**
FUNCTION CreateDC
LPARAMETERS TPDRIVERNAME, TPDEVICENAME, TPOUTPUT, TCDEVMODE
DECLARE INTEGER CreateDC IN Win32API STRING, STRING, STRING, STRING
RETURN CREATEDC(TPDRIVERNAME, TPDEVICENAME, TPOUTPUT, TCDEVMODE)
ENDFUNC
**
FUNCTION DeleteDC
LPARAMETERS THDC
DECLARE LONG DeleteDC IN GDI32 LONG
RETURN DELETEDC(THDC)
ENDFUNC
**
FUNCTION DeleteObject
LPARAMETERS THDC
DECLARE LONG DeleteObject IN GDI32 LONG
RETURN DELETEOBJECT(THDC)
ENDFUNC
**
FUNCTION GetDeviceCaps
LPARAMETERS THDC, TNINDEX
DECLARE INTEGER GetDeviceCaps IN GDI32 LONG, INTEGER
RETURN GETDEVICECAPS(THDC, TNINDEX)
ENDFUNC
**
FUNCTION GetSysColorBrush
LPARAMETERS TNINDEX
DECLARE LONG GetSysColorBrush IN User32 INTEGER
RETURN GETSYSCOLORBRUSH(TNINDEX)
ENDFUNC
**
FUNCTION SetBkColor
LPARAMETERS THDC, TCRCOLOR
DECLARE LONG SetBkColor IN GDI32 LONG, LONG
RETURN SETBKCOLOR(THDC, TCRCOLOR)
ENDFUNC
**
FUNCTION CreateSolidBrush
LPARAMETERS TCRCOLOR
DECLARE LONG CreateSolidBrush IN GDI32 LONG
RETURN CREATESOLIDBRUSH(TCRCOLOR)
ENDFUNC
**
FUNCTION SetBkMode
LPARAMETERS THDC, TIBKMODE
DECLARE INTEGER SetBkMode IN GDI32 LONG, INTEGER
RETURN SETBKMODE(THDC, TIBKMODE)
ENDFUNC
**
FUNCTION GetStockObject
LPARAMETERS TFNOBJECT
DECLARE LONG GetStockObject IN GDI32 INTEGER
RETURN GETSTOCKOBJECT(TFNOBJECT)
ENDFUNC
**
FUNCTION CreatePatternBrush
LPARAMETERS THBMP
DECLARE LONG CreatePatternBrush IN GDI32 LONG
RETURN CREATEPATTERNBRUSH(THBMP)
ENDFUNC
**
FUNCTION GdiSetBatchLimit
LPARAMETERS TDWLIMIT
DECLARE LONG GdiSetBatchLimit IN GDI32 LONG
RETURN GDISETBATCHLIMIT(TDWLIMIT)
ENDFUNC
**
FUNCTION GetTextExtentPoint32
LPARAMETERS THDC, TCSTRING, TNSTRLEN, TPSIZE
DECLARE LONG GetTextExtentPoint32 IN GDI32 LONG, STRING, INTEGER, STRING @
RETURN GETTEXTEXTENTPOINT32(THDC, TCSTRING, TNSTRLEN, @TPSIZE)
ENDFUNC
**
FUNCTION FillRect
LPARAMETERS THDC, TLPRECT, THBRUSH
DECLARE INTEGER FillRect IN User32 LONG, STRING @, LONG
RETURN FILLRECT(THDC, @TLPRECT, THBRUSH)
ENDFUNC
**
FUNCTION DrawText
LPARAMETERS THDC, TLPSTRING, TNCOUNT, TLPRECT, TUFORMAT
DECLARE INTEGER DrawText IN User32 LONG, STRING, INTEGER, STRING @, LONG
RETURN DRAWTEXT(THDC, TLPSTRING, TNCOUNT, @TLPRECT, TUFORMAT)
ENDFUNC
**
FUNCTION ExtTextOut
LPARAMETERS THDC, TNX, TNY, TFUOPTIONS, TLSRECT, TCTEXT, TNTEXTLEN, TLPADX
DECLARE LONG ExtTextOut IN GDI32 LONG, INTEGER, INTEGER, LONG, STRING @, STRING, LONG, STRING @
RETURN EXTTEXTOUT(THDC, TNX, TNY, TFUOPTIONS, @TLSRECT, TCTEXT, TNTEXTLEN, @TLPADX)
ENDFUNC
**
FUNCTION DrawEdge
LPARAMETERS THDC, TLPRECT, TNEDGETYPE, TNBORDERTYPE
DECLARE LONG DrawEdge IN User32 LONG, STRING @, LONG, LONG
RETURN DRAWEDGE(THDC, @TLPRECT, TNEDGETYPE, TNBORDERTYPE)
ENDFUNC
**
FUNCTION CreatePen
LPARAMETERS TFNPENSTYLE, TNWIDTH, TCRCOLOR
DECLARE LONG CreatePen IN GDI32 INTEGER, INTEGER, LONG
RETURN CREATEPEN(TFNPENSTYLE, TNWIDTH, TCRCOLOR)
ENDFUNC
**
FUNCTION MoveToEx
LPARAMETERS THDC, TNX, TNY, TLPPOINT
DECLARE LONG MoveToEx IN GDI32 LONG, INTEGER, INTEGER, STRING @
RETURN MOVETOEX(THDC, TNX, TNY, @TLPPOINT)
ENDFUNC
**
FUNCTION LineTo
LPARAMETERS THDC, TNENDX, TNENDY
DECLARE LONG LineTo IN GDI32 LONG, INTEGER, INTEGER
RETURN LINETO(THDC, TNENDX, TNENDY)
ENDFUNC
**
FUNCTION Rectangle
LPARAMETERS THDC, TNLEFTRECT, TNTOPRECT, TNRIGHTRECT, TNBOTTOMRECT
DECLARE LONG Rectangle IN GDI32 LONG, INTEGER, INTEGER, INTEGER, INTEGER
RETURN RECTANGLE(THDC, TNLEFTRECT, TNTOPRECT, TNRIGHTRECT, TNBOTTOMRECT)
ENDFUNC
**
FUNCTION RoundRect
LPARAMETERS THDC, TNLEFTRECT, TNTOPRECT, TNRIGHTRECT, TNBOTTOMRECT, TNWIDTHCURVE, TNHEIGHTCURVE
DECLARE LONG RoundRect IN GDI32 LONG, INTEGER, INTEGER, INTEGER, INTEGER, INTEGER, INTEGER
RETURN ROUNDRECT(THDC, TNLEFTRECT, TNTOPRECT, TNRIGHTRECT, TNBOTTOMRECT, TNWIDTHCURVE, TNHEIGHTCURVE)
ENDFUNC
**
FUNCTION SetRect
LPARAMETERS TLPRECT, TNLEFT, TNTOP, TNRIGHT, TNBOTTOM
DECLARE LONG SetRect IN User32 STRING @, INTEGER, INTEGER, INTEGER, INTEGER
RETURN SETRECT(TLPRECT, TNLEFT, TNTOP, TNRIGHT, TNBOTTOM)
ENDFUNC
**
FUNCTION GradientFill
LPARAMETERS THDC, TPVERTEX, TDWNUMVERTEX, TPMESH, TDWNUMMESH, TDWMODE
DECLARE LONG GradientFill IN MsImg32 LONG, STRING, LONG, STRING, LONG, LONG
RETURN GRADIENTFILL(THDC, TPVERTEX, TDWNUMVERTEX, TPMESH, TDWNUMMESH, TDWMODE)
ENDFUNC
**
FUNCTION GetPixel
LPARAMETERS THDC, TNXPOS, TNYPOS
DECLARE LONG GetPixel IN GDI32 LONG, INTEGER, INTEGER
RETURN GETPIXEL(THDC, TNXPOS, TNYPOS)
ENDFUNC
**
FUNCTION SetPixelV
LPARAMETERS THDC, TNXPOS, TNYPOS, TNCOLOR
DECLARE LONG SetPixelV IN GDI32 LONG, INTEGER, INTEGER, LONG
RETURN SETPIXELV(THDC, TNXPOS, TNYPOS, TNCOLOR)
ENDFUNC
**
FUNCTION TransparentBlt
LPARAMETERS THDCDEST, TNXDEST, TNYDEST, TNWIDTHDEST, THHEIGHTDEST, THDCSRC, TNXSRC, TNYSRC, TNWIDTHSRC, TNHEIGHTSRC, TCRTRANSPARENT
DECLARE LONG TransparentBlt IN MsImg32 LONG, INTEGER, INTEGER, INTEGER, INTEGER, LONG, INTEGER, INTEGER, INTEGER, INTEGER, LONG
RETURN TRANSPARENTBLT(THDCDEST, TNXDEST, TNYDEST, TNWIDTHDEST, THHEIGHTDEST, THDCSRC, TNXSRC, TNYSRC, TNWIDTHSRC, TNHEIGHTSRC, TCRTRANSPARENT)
ENDFUNC
**
FUNCTION BitBlt
LPARAMETERS THDCDEST, TNXDEST, TNYDEST, TNWIDTHDEST, THHEIGHTDEST, THDCSRC, TNXSRC, TNYSRC, TDWROP
DECLARE LONG BitBlt IN GDI32 LONG, INTEGER, INTEGER, INTEGER, INTEGER, LONG, INTEGER, INTEGER, LONG
RETURN BITBLT(THDCDEST, TNXDEST, TNYDEST, TNWIDTHDEST, THHEIGHTDEST, THDCSRC, TNXSRC, TNYSRC, TDWROP)
ENDFUNC
**
FUNCTION AlphaBlend
LPARAMETERS THDCDEST, TNXDEST, TNYDEST, TNWIDTHDEST, TNHEIGHTDEST, THDCSRC, TNXSRC, TNYSRC, TNWIDTHSRC, TNHEIGHTSRC, TBLENDFUNCTION
DECLARE LONG AlphaBlend IN MsImg32 LONG, INTEGER, INTEGER, INTEGER, INTEGER, INTEGER, INTEGER, INTEGER, INTEGER, INTEGER, INTEGER
RETURN ALPHABLEND(THDCDEST, TNXDEST, TNYDEST, TNWIDTHDEST, TNHEIGHTDEST, THDCSRC, TNXSRC, TNYSRC, TNWIDTHSRC, TNHEIGHTSRC, TBLENDFUNCTION)
ENDFUNC
**
FUNCTION CreateFontIndirect
LPARAMETERS TLPLOGFONT
DECLARE LONG CreateFontIndirect IN GDI32 STRING
RETURN CREATEFONTINDIRECT(TLPLOGFONT)
ENDFUNC
**
FUNCTION ClientToScreen
LPARAMETERS TNHWND, TLPPOINT
DECLARE LONG ClientToScreen IN User32 LONG, STRING @
RETURN CLIENTTOSCREEN(TNHWND, @TLPPOINT)
ENDFUNC
**
FUNCTION ScreenToClient
LPARAMETERS TNHWND, TLPPOINT
DECLARE LONG ScreenToClient IN User32 LONG, STRING @
RETURN SCREENTOCLIENT(TNHWND, @TLPPOINT)
ENDFUNC
**
FUNCTION MapWindowPoints
LPARAMETERS THWNDFROM, THWNDTO, TCPOINTS, TNPOINTCOUNTS
DECLARE INTEGER MapWindowPoints IN User32 LONG, LONG, STRING @, LONG
RETURN MAPWINDOWPOINTS(THWNDFROM, THWNDTO, @TCPOINTS, TNPOINTCOUNTS)
ENDFUNC
**
FUNCTION PtInRect
LPARAMETERS TLPRECT, TNX, TNY
DECLARE LONG PtInRect IN User32 STRING @, LONG, LONG
RETURN PTINRECT(@TLPRECT, TNX, TNY)
ENDFUNC
**
FUNCTION SetCursor
LPARAMETERS THCURSOR
DECLARE LONG SetCursor IN User32 LONG
RETURN SETCURSOR(THCURSOR)
ENDFUNC
**
FUNCTION LoadCursor
LPARAMETERS THINSTANCE, TNCURSORID
DECLARE LONG LoadCursor IN User32 LONG, LONG
RETURN LOADCURSOR(THINSTANCE, TNCURSORID)
ENDFUNC
**
FUNCTION MulDiv
LPARAMETERS TNNUMBER, TNNUMERATOR, TNDENOMINATOR
DECLARE INTEGER MulDiv IN Kernel32 INTEGER, INTEGER, INTEGER
RETURN MULDIV(TNNUMBER, TNNUMERATOR, TNDENOMINATOR)
ENDFUNC
**
FUNCTION CreateRoundRectRgn
LPARAMETERS TNLEFTRECT, TNTOPRECT, TNRIGHTRECT, TNBOTTOMRECT, TNWIDTHELLIPSE, TNHEIGHTELLIPSE
DECLARE LONG CreateRoundRectRgn IN GDI32 INTEGER, INTEGER, INTEGER, INTEGER, INTEGER, INTEGER
RETURN CREATEROUNDRECTRGN(TNLEFTRECT, TNTOPRECT, TNRIGHTRECT, TNBOTTOMRECT, TNWIDTHELLIPSE, TNHEIGHTELLIPSE)
ENDFUNC
**
FUNCTION SelectClipRgn
LPARAMETERS THDC, THREGION
DECLARE INTEGER SelectClipRgn IN GDI32 LONG, LONG
RETURN SELECTCLIPRGN(THDC, THREGION)
ENDFUNC
**
FUNCTION IsThemeActive
DECLARE LONG IsThemeActive IN uxTheme
RETURN ISTHEMEACTIVE()
ENDFUNC
**
FUNCTION RegOpenKey
LPARAMETERS TNHKEY, TCSUBKEY, TNHANDLE
DECLARE INTEGER RegOpenKey IN Win32API INTEGER, STRING, INTEGER @
RETURN REGOPENKEY(TNHKEY, TCSUBKEY, @TNHANDLE)
ENDFUNC
**
FUNCTION RegEnumValue
LPARAMETERS TNHKEY, TNINDEX, TPSZVALUENAME, TPDWSIZE, TWRESERVED, TPDWTYPE, TPBDATA, TPCBDATA
DECLARE INTEGER RegEnumValue IN Win32API INTEGER, INTEGER, STRING @, INTEGER @, INTEGER, INTEGER @, STRING @, INTEGER @
RETURN REGENUMVALUE(TNHKEY, TNINDEX, @TPSZVALUENAME, @TPDWSIZE, TWRESERVED, @TPDWTYPE, @TPBDATA, @TPCBDATA)
ENDFUNC
**
FUNCTION RegCloseKey
LPARAMETERS TNHKEY
DECLARE INTEGER RegCloseKey IN Win32API INTEGER
RETURN REGCLOSEKEY(TNHKEY)
ENDFUNC
**
FUNCTION RegQueryValueEx
LPARAMETERS TNHKEY, TPSZVALUENAME, TWRESERVED, TPDWTYPE, TPBDATA, TPCBDATA
DECLARE INTEGER RegQueryValueEx IN Win32API INTEGER, STRING, INTEGER, INTEGER @, STRING @, INTEGER @
RETURN REGQUERYVALUEEX(TNHKEY, TPSZVALUENAME, TWRESERVED, @TPDWTYPE, @TPBDATA, @TPCBDATA)
ENDFUNC
**
FUNCTION RegCreateKey
LPARAMETERS TNHKEY, TCSUBKEY, TNHANDLE
DECLARE INTEGER RegCreateKey IN Win32API INTEGER, STRING, INTEGER @
RETURN REGCREATEKEY(TNHKEY, TCSUBKEY, @TNHANDLE)
ENDFUNC
**
FUNCTION RegDeleteValue
LPARAMETERS TNHKEY, TCENTRY
DECLARE INTEGER RegDeleteValue IN Win32API INTEGER, STRING
RETURN REGDELETEVALUE(TNHKEY, TCENTRY)
ENDFUNC
**
FUNCTION RegSetValueEx
LPARAMETERS TNHKEY, TPSZENTRY, TWRESERVED, TDWTYPE, TPBDATA, TCBDATA
DECLARE INTEGER RegSetValueEx IN Win32API INTEGER, STRING, INTEGER, INTEGER, STRING, INTEGER
RETURN REGSETVALUEEX(TNHKEY, TPSZENTRY, TWRESERVED, TDWTYPE, TPBDATA, TCBDATA)
ENDFUNC
**
FUNCTION ExtractIconEx
LPARAMETERS TFILE, ICONINDEX, TICONLARGE, TICONSMALL, TNICONS
DECLARE LONG ExtractIconEx IN shell32 STRING @, LONG, LONG @, LONG @, LONG
RETURN EXTRACTICONEX(@TFILE, ICONINDEX, @TICONLARGE, @TICONSMALL, TNICONS)
ENDFUNC
**
FUNCTION DestroyIcon
LPARAMETERS HICON
DECLARE SHORT DestroyIcon IN user32 INTEGER
RETURN DESTROYICON(HICON)
ENDFUNC
**
FUNCTION ExtractAssociatedIcon
LPARAMETERS THINST, TPICONPATH, TPIICON
DECLARE INTEGER ExtractAssociatedIcon IN shell32 INTEGER, STRING @, INTEGER @
RETURN EXTRACTASSOCIATEDICON(THINST, @TPICONPATH, @TPIICON)
ENDFUNC
**
FUNCTION OleCreatePictureIndirect
LPARAMETERS TPICDESC, TREFIID, TFPICTUREOWNSHANDLE, TIPIC
DECLARE LONG OleCreatePictureIndirect IN oleaut32 STRING @, STRING @, LONG, OBJECT @
RETURN OLECREATEPICTUREINDIRECT(TPICDESC, @TREFIID, TFPICTUREOWNSHANDLE, @TIPIC)
ENDFUNC
**
FUNCTION GetLastError
DECLARE INTEGER GetLastError IN kernel32
RETURN GETLASTERROR()
ENDFUNC
**
FUNCTION LockWindowUpdate
LPARAMETERS TNHANDLE
DECLARE INTEGER LockWindowUpdate IN Win32API INTEGER
RETURN LOCKWINDOWUPDATE(TNHANDLE)
ENDFUNC
**
FUNCTION FindExecutable
LPARAMETERS LPFILE, LPDIRECTORY, LPRESULT
DECLARE INTEGER FindExecutable IN Shell32 STRING @, STRING @, STRING @
RETURN FINDEXECUTABLE(@LPFILE, @LPDIRECTORY, @LPRESULT)
ENDFUNC
**
FUNCTION SHGetFileInfo
LPARAMETERS TPSZPATH, TDWFILEATTRIBUTES, TSHFILEINFO, TCBFILEINFO, TUFLAGS
DECLARE LONG SHGetFileInfo IN shell32 STRING, LONG, STRING @, INTEGER, INTEGER
RETURN SHGETFILEINFO(TPSZPATH, TDWFILEATTRIBUTES, @TSHFILEINFO, TCBFILEINFO, TUFLAGS)
ENDFUNC
**
*-*	FUNCTION SendMessage
*-*	LPARAMETERS THWND, TNMSG, TWPARAM, TLPARAM
*-*	DECLARE INTEGER SendMessage IN Win32API INTEGER, INTEGER, INTEGER, STRING
*-*	RETURN SENDMESSAGE(THWND, TNMSG, TWPARAM, TLPARAM)
*-*	ENDFUNC
**
FUNCTION SendMessage
	LPARAMETERS nhWnd, Msg, wParam, Lparam
	*!* 2008-04-18 Changed to wrap SendMessage with a string lParam
	*!* and SendMessage with an integer lParam
	IF VARTYPE(m.lParam) = "C"
		RETURN apiSendMessageString(m.nhWnd, m.Msg, m.wParam, @m.lParam)
	ELSE
		RETURN apiSendMessageInteger(m.nhWnd, m.Msg, m.wParam, m.lParam)
	ENDIF
ENDFUNC
**
FUNCTION apiSendMessageInteger
	LPARAMETERS nhWnd, Msg, wParam, Lparam
	DECLARE INTEGER SendMessage In win32api As apiSendMessageInteger Integer nhWnd, Integer Msg, Integer wParam, Integer Lparam
	RETURN apiSendMessageInteger(m.nhWnd, m.Msg, m.wParam, m.lParam)
ENDFUNC
**
FUNCTION apiSendMessageString
	LPARAMETERS nhWnd, Msg, wParam, Lparam
	DECLARE INTEGER SendMessage In win32api As apiSendMessageString Integer nhWnd, Integer Msg, Integer wParam, String  @Lparam
	RETURN apiSendMessageString(m.nhWnd, m.Msg, m.wParam, @m.lParam)
ENDFUNC
**
FUNCTION GetComputerName
LPARAMETERS TCBUFFER, TNSIZE
DECLARE INTEGER GetComputerName IN kernel32 STRING @, INTEGER @
RETURN GETCOMPUTERNAME(@TCBUFFER, @TNSIZE)
ENDFUNC
**
FUNCTION GetVolumeInformation
LPARAMETERS TPROOTPATHNAME, TPVOLNAMEBUF, TNVOLNAMESZ, TPVOLSERIALNUM, TPMAXCOMPLEN, TPFILESYSFLAGS, TPFILESYSNAMEBUF, TNFILESYSNAMESZ
DECLARE INTEGER GetVolumeInformation IN WIN32API STRING @, STRING @, INTEGER, INTEGER @, INTEGER @, INTEGER @, STRING @, INTEGER
RETURN GETVOLUMEINFORMATION(@TPROOTPATHNAME, @TPVOLNAMEBUF, TNVOLNAMESZ, @TPVOLSERIALNUM, @TPMAXCOMPLEN, @TPFILESYSFLAGS, @TPFILESYSNAMEBUF, TNFILESYSNAMESZ)
ENDFUNC
**
FUNCTION GetShortPathName
LPARAMETERS TCLONGNAME, TCSHORTNAME, TNSIZEOF
DECLARE LONG GetShortPathName IN Win32API STRING, STRING @, LONG
RETURN GETSHORTPATHNAME(TCLONGNAME, @TCSHORTNAME, TNSIZEOF)
ENDFUNC
**
FUNCTION BringWindowToTop
LPARAMETERS THWND
DECLARE INTEGER BringWindowToTop IN Win32API INTEGER
RETURN BRINGWINDOWTOTOP(THWND)
ENDFUNC
**
FUNCTION ShellExecute
LPARAMETERS TNHWND, TLPACTION, TLPFILE, TLPPARAMS, TLPDIRECTORY, TNSHOWCMD
DECLARE INTEGER ShellExecute IN Shell32 LONG, STRING, STRING, STRING, STRING, INTEGER
RETURN SHELLEXECUTE(TNHWND, TLPACTION, TLPFILE, TLPPARAMS, TLPDIRECTORY, TNSHOWCMD)
ENDFUNC
**
FUNCTION GetKeyState
LPARAMETERS TKEYCODE
DECLARE SHORT GetKeyState IN User32 INTEGER
RETURN GETKEYSTATE(TKEYCODE)
ENDFUNC
**
FUNCTION GetAsyncKeyState
LPARAMETERS TKEYCODE
DECLARE SHORT GetAsyncKeyState IN User32 INTEGER
RETURN GETASYNCKEYSTATE(TKEYCODE)
ENDFUNC
**
FUNCTION GetKeyboardState
LPARAMETERS TCKEYCODES
DECLARE INTEGER GetKeyboardState IN user32 STRING @
RETURN GETASYNCKEYSTATE(@TCKEYCODES)
ENDFUNC
**
FUNCTION KillTimer
LPARAMETERS TNHWND, TNIDEVENT
DECLARE LONG KillTimer IN User32 LONG, LONG
RETURN KILLTIMER(TNHWND, TNIDEVENT)
ENDFUNC
**
FUNCTION SetTimer
LPARAMETERS TNHWND, TNIDEVENT, TUELAPSE, TLPTIMERFUNC
DECLARE LONG SetTimer IN User32 LONG, LONG, LONG, LONG
RETURN SETTIMER(TNHWND, TNIDEVENT, TUELAPSE, TLPTIMERFUNC)
ENDFUNC
**
FUNCTION GetSystemDirectory
LPARAMETERS TPBUFFER, TNSIZE
DECLARE INTEGER GetSystemDirectory IN kernel32 STRING @, INTEGER
RETURN GETSYSTEMDIRECTORY(@TPBUFFER, TNSIZE)
ENDFUNC
**
FUNCTION GetSystemMetrics
LPARAMETERS TNINDEX
DECLARE INTEGER GetSystemMetrics IN User32 INTEGER
RETURN GETSYSTEMMETRICS(TNINDEX)
ENDFUNC
**
FUNCTION GetSysColor
LPARAMETERS TNINDEX
DECLARE LONG GetSysColor IN User32 INTEGER
RETURN GETSYSCOLOR(TNINDEX)
ENDFUNC
**
FUNCTION SetTextColor
LPARAMETERS THDC, TCRCOLOR
DECLARE LONG SetTextColor IN GDI32 LONG, LONG
RETURN SETTEXTCOLOR(THDC, TCRCOLOR)
ENDFUNC
**
FUNCTION MoveWindow
LPARAMETERS THWND, TNX, TNY, TNWIDTH, TNHEIGHT, TBREPAINT
DECLARE LONG MoveWindow IN User32 LONG, INTEGER, INTEGER, INTEGER, INTEGER, LONG
RETURN MOVEWINDOW(THWND, TNX, TNY, TNWIDTH, TNHEIGHT, TBREPAINT)
ENDFUNC
**
FUNCTION SetWindowPos
LPARAMETERS TNHWND, THWNDINSERTAFTER, TNX, TNY, TNWIDTH, TNHEIGHT, TUFLAGS
DECLARE LONG SetWindowPos IN User32 LONG, LONG, INTEGER, INTEGER, INTEGER, INTEGER, LONG
RETURN SETWINDOWPOS(TNHWND, THWNDINSERTAFTER, TNX, TNY, TNWIDTH, TNHEIGHT, TUFLAGS)
ENDFUNC
**
FUNCTION WindowFromPoint
LPARAMETERS TNX, TNY
DECLARE LONG WindowFromPoint IN User32 LONG, LONG
RETURN WINDOWFROMPOINT(TNX, TNY)
ENDFUNC
**
FUNCTION GetDesktopWindow
DECLARE INTEGER GetDesktopWindow IN user32
RETURN GETDESKTOPWINDOW()
ENDFUNC
**
FUNCTION GetWindowDC
LPARAMETERS TNHWND
DECLARE LONG GetWindowDC IN User32 LONG
RETURN GETWINDOWDC(TNHWND)
ENDFUNC
**
FUNCTION SetWindowLong
LPARAMETERS TNHWND, TNINDEX, TDWNEWLONG
DECLARE INTEGER SetWindowLong IN user32 INTEGER, INTEGER, INTEGER
RETURN SETWINDOWLONG(TNHWND, TNINDEX, TDWNEWLONG)
ENDFUNC
**
FUNCTION CallWindowProc
LPARAMETERS TLPPREVWNDFUNC, TNHWND, TUMSG, TWPARAM, TLPARAM
DECLARE LONG CallWindowProc IN User32 LONG, LONG, LONG, LONG, LONG
RETURN CALLWINDOWPROC(TLPPREVWNDFUNC, TNHWND, TUMSG, TWPARAM, TLPARAM)
ENDFUNC
**
FUNCTION GetWindowLong
LPARAMETERS TNHWND, TNINDEX
DECLARE LONG GetWindowLong IN User32 LONG, INTEGER
RETURN GETWINDOWLONG(TNHWND, TNINDEX)
ENDFUNC
**
FUNCTION GetWindow
LPARAMETERS TNHWND, TWFLAG
DECLARE INTEGER GetWindow IN user32 INTEGER, INTEGER
RETURN GETWINDOW(TNHWND, TWFLAG)
ENDFUNC
**
FUNCTION GetWindowText
LPARAMETERS THWND, TPSTRING, TCCH
DECLARE INTEGER GetWindowText IN user32 INTEGER, STRING @, INTEGER
RETURN GETWINDOWTEXT(THWND, @TPSTRING, TCCH)
ENDFUNC
**
FUNCTION ShowWindow
LPARAMETERS TNHWND, TNCMDSHOW
DECLARE INTEGER ShowWindow IN win32api INTEGER, INTEGER
RETURN SHOWWINDOW(TNHWND, TNCMDSHOW)
ENDFUNC
**
FUNCTION IsIconic
LPARAMETERS THWND
DECLARE INTEGER IsIconic IN user32 INTEGER
RETURN ISICONIC(THWND)
ENDFUNC
**
FUNCTION BringWindowToTop
LPARAMETERS THWND
DECLARE SHORT BringWindowToTop IN user32 INTEGER
RETURN BRINGWINDOWTOTOP(THWND)
ENDFUNC
**
FUNCTION GetWindowRect
LPARAMETERS TNHWND, TLPRECT
DECLARE LONG GetWindowRect IN User32 LONG, STRING @
RETURN GETWINDOWRECT(TNHWND, @TLPRECT)
ENDFUNC
**
FUNCTION HeapFree
LPARAMETERS THHEAP, TDWFLAGS, TLPHEAP
DECLARE LONG HeapFree IN Kernel32 LONG, LONG, LONG
RETURN HEAPFREE(THHEAP, TDWFLAGS, TLPHEAP)
ENDFUNC
**
FUNCTION HeapAlloc
LPARAMETERS THHEAP, TDWFLAGS, TDWBYTES
DECLARE LONG HeapAlloc IN Kernel32 LONG, LONG, LONG
RETURN HEAPALLOC(THHEAP, TDWFLAGS, TDWBYTES)
ENDFUNC
**
FUNCTION HeapDestroy
LPARAMETERS THHEAP
DECLARE LONG HeapDestroy IN Kernel32 LONG
RETURN HEAPDESTROY(THHEAP)
ENDFUNC
**
FUNCTION HeapCreate
LPARAMETERS TFLOPTIONS, TDWINITIALSIZE, TDWMAXIMUMSIZE
DECLARE LONG HeapCreate IN Kernel32 LONG, LONG, LONG
RETURN HEAPCREATE(TFLOPTIONS, TDWINITIALSIZE, TDWMAXIMUMSIZE)
ENDFUNC
**
FUNCTION lstrlen
LPARAMETERS TLPSTRING
DECLARE INTEGER lstrlen IN Kernel32 LONG
RETURN LSTRLEN(TLPSTRING)
ENDFUNC
**
FUNCTION lstrlenW
LPARAMETERS TLPSTRING
DECLARE INTEGER lstrlenW IN Kernel32 LONG
RETURN LSTRLENW(TLPSTRING)
ENDFUNC
**
FUNCTION HeapSize
LPARAMETERS THHEAP, TNALLOC, TNADDR
DECLARE INTEGER HeapSize IN Win32Api INTEGER, INTEGER, INTEGER
RETURN HEAPSIZE(THHEAP, TNALLOC, TNADDR)
ENDFUNC
**
FUNCTION GetUserName
LPARAMETERS TPBUFFER, TNSIZE
DECLARE INTEGER GetUserName IN advapi32.dll STRING @, INTEGER @
RETURN GETUSERNAME(@TPBUFFER, @TNSIZE)
ENDFUNC
**
