*-*	Constants for DEVMODE
#DEFINE CCHFORMNAME        32
#DEFINE CCHDEVICENAME      32
#DEFINE DM_FORMNAME        0x10000
#DEFINE DM_ORIENTATION     0x1
#DEFINE DM_PAPERSIZE       0x2
#DEFINE DM_PAPERLENGTH     0x4
#DEFINE DM_PAPERWIDTH      0x8

*-*	Constants for DocumentProperties() call
#DEFINE DM_MODIFY          8
#DEFINE DM_IN_BUFFER       DM_MODIFY
#DEFINE DM_COPY            2
#DEFINE DM_OUT_BUFFER      DM_COPY
#DEFINE DMORIENT_PORTRAIT  1
#DEFINE DMORIENT_LANDSCAPE 2
