#DEFINE ERR_NO_ERROR             0 
#DEFINE ERR_BAD_PARAMS          -11
#DEFINE ERR_DEF_NOT_LOADED     -301 
#DEFINE ERR_DEF_ALREADY_LOADED -302 
#DEFINE ERR_INVALID_DEF        -303 
#DEFINE ERR_INVALID_DEF_NAME   -304 
#DEFINE ERR_INVALID_ARRAY      -305 
#DEFINE ERR_NO_MEMBERS         -306 
#DEFINE ERR_INVALID_DATA_IN    -307 
#DEFINE ERR_2_LEVEL_STRUCT     -308 
#DEFINE ERR_DLL_EXCEPTION      -309 

#DEFINE DATA_8           "8"
#DEFINE DATA_16         "16"
#DEFINE DATA_32         "32"
#DEFINE DATA_64         "64"
#DEFINE DATA_VB         "VB"
#DEFINE DATA_INT_STRUCT "IS"

#DEFINE IDX_FILETIME   1
#DEFINE IDX_POINT      2
#DEFINE IDX_POINTL     3
#DEFINE IDX_RECT       4
#DEFINE IDX_RECTL      5
#DEFINE IDX_SYSTEMTIME 6

#DEFINE CLIP_NORMAL    0
#DEFINE CLIP_FORCE     1
#DEFINE CLIP_INFO      2
#DEFINE CLIP_FORCE_AND_INFO CLIP_FORCE+CLIP_INFO && 3

#DEFINE CRLF    CHR(13)+CHR(10)
#DEFINE True    .T.
#DEFINE False   .F.

#DEFINE LEN_LINE    255

#DEFINE INT_STRUCT    0
#DEFINE EXT_STRUCT    1
#DEFINE BOOL_C        2
#DEFINE DOUBLE_C      3
#DEFINE DWORD_C       4
#DEFINE FLOAT_C       5
#DEFINE QWORD_C       6
#DEFINE TCHAR_C       7
#DEFINE WCHAR_C       8
#DEFINE WORD_C        9
#DEFINE CHARFAR_C    10

#DEFINE ADD_ARRAY "["+LTRIM(STR(ii))+"]"

#DEFINE DBL_BIAS_EXP   1023
#DEFINE FTL_BIAS_EXP    127
#DEFINE DBL_L_EXP        11
#DEFINE FTL_L_EXP         8
#DEFINE DBL_L_MANT       52
#DEFINE FTL_L_MANT       23
#DEFINE DBL_DECIM        15
#DEFINE FLT_DECIM         6

#DEFINE A_END CHR(0)        && ansi
#DEFINE U_END CHR(0)+CHR(0) && unicode

#DEFINE GMEM_FIXED 0

#DEFINE TOP_API_ARRAY     "struct _APIARRAY {"
#DEFINE END_API_ARRAY     "} APIARRAY"
